= Teilnehmende

:page-partial:

*Teilnehmende* von Decidim können in drei verschiedene Kategorien gruppiert werden:

* *Besucher* haben Zugang zu allen Inhalten der Plattform, ohne sich registrieren zu müssen oder Informationen zur Verfügung zu stellen.
* *Registrierte* Teilnehmende können Vorschläge und Kommentare einreichen, sich für Veranstaltungen anmelden, Inhalte bestätigen, anderen Teilnehmenden folgen und Mitteilungen, Erwähnungen und private Nachrichten erhalten.
Nutzende können sich *direkt* auf der Plattform oder über Gateways anderer *sozialer Netzwerke* registrieren (Facebook, Twitter oder Google+). Um sich direkt zu registrieren, müssen Nutzende ein E-Mail-Konto und ein Passwort mit dem Benutzerkonto verknüpfen.
 Registrierte Teilnehmende können auch ihr Konto amtlich bestätigen lassen (d. h. ihr Benutzername wird von einem speziellen Symbol begleitet, das anzeigt, dass sie wirklich die Person sind, die sie in ihrem Profil vorgeben zu sein).
* *Verifizierte* Teilnehmende können Entscheidungen treffen. Decidim bietet verschiedene Möglichkeiten, diese Überprüfung durchzuführen.

Admins können *Berechtigungen* für *registrierte* und *verifizierte* Nutzende selektiv *verwalten*. Zum Beispiel kann _Vorschlagserstellung_ sowohl für registrierte als auch verifizierte Nutzende aktiviert werden, aber _Unterstützungen für Vorschläge_ nur für verifizierte Nutzende.

== Öffentliche Registrierung von administrativen Aktivitäten

Die manuelle Prüfung der Teilnehmenden sowie andere administrative Massnahmen können eine Schwachstelle schaffen oder die Admins in die Lage versetzen, die Plattform auf missbräuchliche Weise zu nutzen. Um es zu vermeiden, enthält Decidim ein *öffentliches Register der administrativen Aktivitäten*, damit diese Aktionen öffentlich und transparent geprüft werden können.

== Benutzerprofil und persönliche Einstellungen

Es gibt eine **Benutzerprofilseite**, auf der die Teilnehmenden **Änderungen an ihren Daten vornehmen** können (wie E-Mail-Konto, Passwort usw.), ein *Avatar*-Bild hochladen und aktivieren, Benachrichtigungen einstellen oder ihr Konto löschen.

Auf der Benutzerprofilseite können Teilnehmende *zusätzliche Informationen* hinzufügen, um Interessen und Fähigkeiten einzubeziehen, freiwillig und durch Auswahl des Niveaus der Sichtbarkeit dieser Informationen. Dadurch können persönliche Benachrichtigungen gesendet werden, und Teilnehmende können für Kooperationen mit anderen zusammengeführt werden.

== Überwachung und Benachrichtigungen

Teilnehmende erhalten *automatisierte Benachrichtigungen* zu dem Inhalt, den sie erstellt haben: Antworten auf Kommentare und Kommentare zu ihren Vorschlägen sowie die Ergebnisse ihrer Vorschläge (ob angenommen oder abgelehnt).

Neben automatisierten Benachrichtigungen können sich die Teilnehmenden dazu entschliessen, jedem Element des Systems **zu folgen** (andere Vorschläge, Ergebnisse, Prozesse, Versammlungen, Initiativen, Gruppen oder Nutzende usw.) und Benachrichtigungen zu erhalten.

== Kommunikation zwischen Teilnehmenden

**Sofortnachrichten **können an Teilnehmende über die Plattform gesendet werden, die eine E-Mail-Benachrichtigung erhalten.

*Erwähnungen* können auch im Kommentarbereich jedem registrierten Benutzer hinzugefügt werden und eine Benachrichtigung wird automatisch versendet.

== Benutzergruppen

Teilnehmende können sich bei der Plattform als Mitglieder einer oder mehrerer Organisationen/Kollektive anmelden. Sobald die Organisation und der Mitgliedsstatus überprüft wurden, können die Teilnehmenden Aktionen durchführen (Vorschläge machen, Kommentare einreichen usw.), unter ihrem eigenen Namen oder mit dem Organisationsnamen.

Benutzergruppen können auch Benutzerberechtigungen und Administrationsrollen verwalten, die Gruppen zugewiesen werden, sowie private Diskussionsräume oder Informationen beispielsweise unter Gruppennutzern, die an einer persönlichen Veranstaltung teilgenommen haben, austauschen. [Funktion fehlt]

== Engagement

Decidim hat eine Reihe von Funktionen, die auf die *Gamifizierung* der Plattform ausgerichtet sind, um eine wachsende Anzahl von Teilnehmenden anzuziehen und ihr Interesse zu erhalten, sowie um Praktiken zu fördern, die die demokratische Qualität und kollektive Intelligenz in der Partizipation stärken [das Gamification-System wird für 2018Q2-3, AjB-Lote1 erwartet].

Das Gamifizierungssystem umfasst zwei Modi, einen für die Nutzenden und den anderen für Vorschläge.

* Der **benutzerzentrierte **Modus beinhaltet ein *Punktesystem* basierend auf mehreren Kriterien (Grad der Detailliertheit des Benutzerprofils, Anzahl der Einladungen an andere auf der Plattform, Anzahl der unterbreiteten und kommentierten Vorschläge, Anzahl der Kommentare, Anzahl der erhaltenen Bestätigungen, Anzahl der Follower, usw.

Die Kombination dieser und anderer Indikatoren dient der Generierung von Gamification-Pfaden für jede nutzende Person und der Definition von Themen wie: die meisten teilnehmenden Personen im Distrikt, Führung in Diskussionen und Debatten usw.

* Die Gamification *mit Fokus auf Vorschläge/Initiativen* erlaubt es Initiierenden, Unterzeichnenden und Followern, die Interaktion mit ihnen zu fördern, indem mehrere *Metriken* einbezogen werden (Anzahl der Male, die der Vorschlag in sozialen Netzwerken geteilt wird, Grad der Kontroverse (Anzahl der positiven und negativen Kommentare), Qualität der Beratung (Tiefe des Diskussionsbaums), Anzahl der erhaltenen Aufrufe usw.