= Beteiligte Räume

:page-partial:

Partizipatorische Räume definieren die wichtigsten partizipatorischen Kanäle. Sie werden im Hauptmenü der Plattform angezeigt.

Die grundlegende Logik hinter der Struktur von Decidim ist, dass *Komponenten in den partizipatorischen Räumen* zusammenarbeiten. Es gibt verschiedene Arten von Räumen (Initiativen, Prozesse, Konsultationen und Versammlungen) und verschiedene Instanzen innerhalb jeder Art (ein Wahlprozess und ein anderer für Beteiligungshaushalte, ein Ratsgremium für die Nachbarschaft und ein anderes für die Arbeitnehmer, eine Initiative, um eine Änderung der Gesetzgebung zu fordern, und eine andere, um etwas in die Tagesordnung einer Plenartagung einzubeziehen, usw.).

== Prozesse

Beteiligungsprozesse erfordern ein generelles *Konfigurationsformular* mit den folgenden Feldern: Titel oder Name des Prozesses; Kurzname für die URL; Hashtag (wird als Referenz für die Kommunikation in sozialen Netzwerken verwendet); kurze Beschreibung; lange Beschreibung; Startseitenbild; Bannerbild; Start- und Enddatum; Themenfeld; Trägergruppe (verantwortlich für den partizipatorischen Prozess auf politischer Ebene, kann die Kommunalbehörde oder eine Gruppe aus Fachleuten der Behörde, Politikerinnen und Politikern sowie Verbänden und anderen Organisationen sein); an wen sie sich richtet; Ziel des partizipatorischen Prozesses und partizipatorische Struktur. Durch den Beteiligungsprozess können *begleitende Dokumente* hinzugefügt werden.

Die Beteiligungsprozesse werden in *Stufen* unterteilt (z. B. 1. Information und Einberufung der Etappe; 2. diagnostische Phase; 3. Vorschläge Etappe; 4. priorsation stage; 5. Entscheidungsphase; 6. Evaluierungsphase und 7. Ergebnisüberwachung). Jede Stufe enthält die folgenden Konfigurationsfelder: Titel, Beschreibung, Startdatum, Enddatum.

*Hervorhebungen von Ankündigungen oder Texten* können auch in den Prozessen angezeigt werden, sowohl auf der Homepage als auch in der Rubrik der einzelnen Komponenten (Vorschläge, Diskussionen und Debatten, usw.) Verschiedene Nachrichten können je nach der jeweiligen Phase eines Prozesses konfiguriert werden.

Ein *Konfigurationswerkzeug für Beteiligungsprozesse* ermöglicht die einfache Aktivierung und Deaktivierung von Stufen und deren Komponenten. Decidims Prozesskonfigurationswerkzeug ist eines seiner leistungsstärksten Features, da es völlige Flexibilität bei der Gestaltung von Beteiligungsprozessen nach den verschiedenen Realitäten und Formen der Bürgerbeteiligung ermöglicht.

Die Funktion **Prozessgruppen ermöglicht die Zusammenlegung verschiedener Prozesse, wie etwa der Teilhaberhaushalte verschiedener Distrikte oder Stadtviertel.

Beteiligungsprozesse können einen der folgenden *Prozessstatus* haben: 0) veröffentlicht oder unveröffentlicht; 1) offen (gestartet); 2) geschlossen (der Beteiligungsprozess ist beendet, aber seine Ergebnisse sind noch im Gange); 3) beendet (sowohl der Prozess als auch seine Ergebnisse sind abgeschlossen) und 4) Zukunft (hat noch nicht begonnen).

Ein Prozess kann **markiert** sein (erhöht die Sichtbarkeit auf der Homepage).

Es besteht auch die Möglichkeit, aus dem Administrationsbereich **Beteiligungsprozesse zu kopieren**. Mit dieser Funktion können Prozessmodelle so gestaltet und kopiert werden, dass bestimmte Details innerhalb der neuen Prozesse konfiguriert werden können Vermeidung der Notwendigkeit, sie von Grund auf neu zu erstellen.

== Versammlungen

Decidim erlaubt die **Schaffung und Konfiguration** von partizipatorischen oder staatlichen *Versammlungen* (Regierungs- oder partizipatorische Organe; Räte, Arbeitsgruppen, usw.) als strukturierte Teilnehmendengruppen definiert werden, die sich sowohl auf individueller als auch auf repräsentativer Ebene regelmässig treffen und befugt sind, Vorschläge und Entscheidungen zu treffen.

Im Bereich der *Versammlungen* können Sie eine vollständige Liste aller Versammlungen sehen, die im Administrationsbereich aktiviert und konfiguriert sind. Die grundlegenden *Einstellungen* erfordern, dass die folgenden Felder für jedes Gremium ausgefüllt werden: Name; Bild; Thema (global, territorial oder sektoral); Funktion des Gremiums (Zweck der Massnahme); Art des Gremiums (Regierung, Exekutive, Beratung / beratend, partizipativ, Arbeitsgruppe, Kommission usw.); Erstellungsdatum; auf Initiative von (Stadtrat, Bevölkerung oder anderen); Dauer (unbegrenzt oder befristet, im letzteren Fall mit Enddatum); Datum der Aufnahme in Decidim; Datum der Schliessung und Begründung; wie es organisiert ist (Funktionen, Befugnisse usw.); Zusammensetzung; ob ein Beitritt möglich ist und wie das geht; Methode der Mitgliederwahl; Typ/Funktion der Mitglieder innerhalb des Gremiums; Zusammensetzung interner Arbeitsgruppen wie Begleit- oder Beratungsausschüsse; Merkmale des Gremiums; die sozialen Netzwerke des Gremiums (Name des sozialen Netzwerks und Link) sowie die nächsten Veranstaltungen des Gremiums.

* *Einberufung von Veranstaltungen*: ermöglicht das Versenden automatischer Veranstaltungseinladungen, die gemeinsame Erstellung von Tagesordnungen und die Registrierung der Teilnehmenden. Eine komplette Liste der Funktionen finden Sie in der Komponente "Veranstaltungen".
* *Charakteristika der Versammlung*: offene, öffentliche, transparente und andere Charakteristika bezüglich des Niveaus der Teilnahme, die die Versammlung zulässt.
* *Zusammensetzung:* Dadurch kann die Zusammensetzung des Gremiums detaillierter definiert werden, unter Verwendung der Profile der mit dem Gremium assoziierten Teilnehmenden sowie anderer Merkmale. Eine Darstellung der Körperstruktur wird automatisch anhand der Zusammensetzung der teilnehmenden Mitglieder generiert:
** *Arten von Mitgliedern*: Vorsitzende, stellvertretende Vorsitzende, Schriftführende, andere
** *Herkunft der Mitgliedschaft*: durch Auslosung, Direktwahl, Vertretung einer anderen Versammlung, Regierungsvertretung usw.
** *Interne Arbeitsgruppen*: zur Erstellung von Untergruppen. Arbeitsgruppen können sich auf den Körper beziehen, dem sie angehören
** *Charakteristiken*: offen/geschlossen; transparent; mit verschiedenen Zugriffsgenehmigungen.
* *Anzeigen*: erlaubt es uns, interne Daten über jedes Gremium sowie die Verbindungen zwischen den Versammlungen anzuzeigen
** *Zusammensetzung*: Die Struktur eines Körpers wird in Form eines Kreisdiagramms angezeigt
** *Organisationsdiagramme*: erlauben uns, die Hierarchie oder das Netzwerk von Versammlungen und deren Assoziationen zu sehen.
* *Karte und Kalender*: erlauben uns, den Standort aller Versammlungen auf einer Karte und einem Kalender zu sehen
* *Involvierung mit anderen Räumen und Komponenten*
** *Beteiligung an Prozessen*: Assemblies können Promoter-Gruppen sein, einen Prozess starten oder Vorschläge in einem Prozess machen. Die Zusammensetzung eines Körpers kann das Ergebnis eines Prozesses (bei der Auswahl von Beiträgen) sein
** *Vorschläge und Ergebnisse*: ein Gremium kann seine eigenen Vorschläge oder Ergebnisse erstellen.
*** Er zeigt, wie der Vorschlag angenommen wurde (durch Konsens, Mehrheit, Stimmenzahl usw.).
** *Veranstaltungen*: Versammlungen werden eine Liste der zugehörigen Veranstaltungen haben, aber einige Merkmale können von einer Veranstaltung zur anderen springen, wie Bürgerinitiativen zur Aufnahme eines Punktes in eine Agenda. Ebenso muss es möglich sein, Protokolle getrennt von der Veranstaltung zu sehen, da sie direkt mit dem Gremium verbunden sind.

== Initiativen

*Initiativen*. Dieser partizipatorische Raum erlaubt es den Bürgern, Vorschläge zu machen und die *erforderliche Anzahl an Unterschriften und/oder Unterstützungen* je nach Typ zu sammeln (die verschiedenen Typen sind in den kommunalen Vorschriften festgelegt), der Beginn des Verwaltungsverfahrens für seine Verarbeitung und die Überwachung der Bürger.

Initiativen funktionieren wie folgt:

* Jede Person oder Bürgervereinigung kann einen Vorschlag für eine Bürgerinitiative unterbreiten. Es gibt *mehrere Arten von Initiativen* mit verschiedenen Nummern von Unterstützungen/Unterschriften für ihre Verarbeitung (alle sind konfigurierbar). Auf der Initiativ-Erstellungsseite kann eine Beschreibung der einzelnen Methoden, der benötigten Unterschriften und Beispiele (z.B. erklärende Videos) angezeigt werden.
* Um Doppelarbeit zu vermeiden, sobald eine Initiative erstellt wurde, wird das System Vorschläge für **ähnliche Initiativen** vorlegen, bevor Sie mit dem folgenden Schritt fortfahren. Sobald ähnliche Vorschläge ausgeschlossen sind, wird die konkrete Form für jede Art von Initiative angezeigt, zusammen mit der erforderlichen Mindestanzahl von Bestätigungen. Der Urheber hat dann eine URL zur Verfügung, mit der andere zur Teilnahme eingeladen werden und die Initiative unterstützt werden kann. Es wird auch eine Karte angezeigt, die die Orte der Begegnungspunkte anzeigt, um Unterschriften zu sammeln, falls eine vorhanden ist.
* Sobald die Initiative ins Leben gerufen wurde, wird die Initiative zu einer **technischen Moderations- und Validierungsphase** übergehen, wo die Mitarbeiter des Stadtrats auf verschiedene Weise reagieren können (durch Zustimmung, Ablehnung oder Änderungsvorschläge).
* Initiativen können überwacht werden und **Benachrichtigungen über aktualisierte** Status erhalten, zusätzlich können ihre einzelnen Initiierenden oder Gruppen regelmässig Informations-Newsletter an andere Teilnehmende der Plattform senden, die sich dafür entschieden haben, der Initiative zu folgen.
* Beim Erreichen des festgelegten Enddatums kann eine Initiative zwei mögliche Staaten haben:
** *Abgelehnt*: wenn die Mindestanzahl der Signaturen nicht erreicht wird, wird eine Nachricht mit dem Titel "erfüllt nicht die erforderliche Anzahl von Unterschriften" angezeigt und der Urheber der Initiative wird benachrichtigt.
** *Akzeptiert*: Wenn eine ausreichende Anzahl von Unterschriften oder Zustimmungen erreicht wurde, wird sie angenommen und das entsprechende Verfahren wird gestartet.

== Konsultationen

Konsultationen (ein Abstimmungsverfahren, bei dem alle Teilnehmenden der Organisation zur Abstimmung über bestimmte Fragen aufgefordert werden) ermöglichen es den Teilnehmenden, **sich über aktuelle oder zukünftige Konsultationen zu informieren**, den Themenbereich der Konsultation *zu diskutieren und zu debattieren* sowie die Ergebnisse *zu überwachen*. Es stellt auch ein *Gateway zu einem e-vote-System* zur Verfügung, das extern zu Decidim ist, aber in die Schnittstelle integriert ist, um Identitäten zu verwalten und zu verifizieren.