= {page-component-title}
include::translations::partial$attributes.adoc[]

ifeval::["{page-subtitle}" != ""]
[.lead]
{page-subtitle}
endif::[]

ifeval::["{description}" != ""]
[abstract]
{description}
endif::[]

== Metadatos del documento

[cols="20,80"]
|===
| *Título*                              | *{page-component-title}*

ifeval::["{page-subtitle}" != ""]
| Subtítulo                             | {page-subtitle}
endif::[]

ifeval::["{page-component-version}" != "master"]
| Versión                               | {page-component-version}
endif::[]

ifeval::["{revdate}" != ""]
| Fecha                                 | {revdate}
endif::[]

ifeval::["{page-editors}" != ""]
| Edición                               | {page-editors}
endif::[]

| *Autoría*                             | *{authors}*

ifeval::["{page-contributors}" != ""]
| Contribución                          | {page-contributors}
endif::[]

ifeval::["{page-proofreaders}" != ""]
| Revisión                              | {page-proofreaders}
endif::[]

ifeval::["{page-participants}" != ""]
| Participación                         | {page-participants}
endif::[]

ifeval::["{page-translators}" != ""]
| Traducción                            | {page-translators}
endif::[]

| Palabras clave                        | {keywords}

ifeval::["{page-history}" != ""]
| Historia del documento                | {page-history}
endif::[]

ifeval::["{page-zotero-id}" != ""]
| Cómo se cita                          | {page-zotero-id}
endif::[]

| Copyleft
a| _{page-copyright-ownership}_, bajo
ifeval::["{page-license-alternative}" == ""]
una licencia _{page-license}_.
endif::[]
ifeval::["{page-license-alternative}" != ""]
las licencias _{page-license}_ y _{page-license-alternative}_.
endif::[]


[discrete]
=== Creative Commons Reconocimiento-CompartirIgual 4.0 Internacional (CC-BY-SA-4.0)

Usted es libre de copiar y redistribuir el material en cualquier medio o formato, remezclar, transformar y crear a partir del material, para cualquier finalidad, incluso comercial.
El licenciador no puede revocar estas libertades mientras cumpla con los términos de la licencia.
Bajo las siguientes condiciones: a) Reconocimiento: debe reconocer adecuadamente la autoría, proporcionar un enlace a la licencia e indicar si se han realizado cambios.
Puede hacerlo de cualquier manera razonable, pero no de una manera que sugiera que tiene el apoyo del licenciador o lo recibe por el uso que hace; b) compartir igual: si remezcla, transforma o crea a partir del material, deberá difundir sus contribuciones bajo la misma licencia que el original.
No hay restricciones adicionales, no puede aplicar términos legales o medidas tecnológicas que legalmente restrinjan realizar aquello que la licencia permite.
Puede encontrar las licencias completas en los siguientes enlaces: https://creativecommons.org/licenses/by-sa/4.0/deed.es_ES.

[discrete]
=== GFDL: Licencia de Documentación Libre de GNU (GFDL-1.3-or-later)

Se concede permiso para copiar, distribuir y/o modificar este documento bajo los términos de la licencia de documentación libre GNU, versión 1.3 o cualquier otra versión posterior publicada por la Free Software Foundation; sin secciones invariantes ni textos de cubierta delantera, tampoco textos de contraportada.
Una copia de la licencia se puede encontrar en http://www.gnu.org/copyleft/fdl.html.
|===
