= Information pages

include::partial$legacy.adoc[]

Here we offer you three informative pages that you can use as a template or re-use replacing the text highlighted in yellow with the correct text. You can find the same documents in spanish or catalan in their respective Administering Decidim document.

== Information/FAQs

[[t.6a4146f0a2c8ecae39afa2642bcb7f700ef842af]][[t.0]]

[width="100%",cols="100%",]
|===
|_FAQS (EN)_
a|
If you’d like to take part in participatory processes and have your say, register! Note that to use some of the functions of certain processes (such as voting and prioritising) you will have to verify that you are registered with #Name of the Municipality/ Organization#, by following a very simple step.

*What is #Name of the Municipality/ Organization?#*

A platform for building a more participatory #Name of the Municipality/ Organization#, with a shared vision and for delving deeper into local participatory democracy.

#Platformname# is a participatory platform based on open code. Citizens can see how it is built and can reuse or improve it. https://www.google.com/url?q=https://github.com/AjuntamentdeBarcelona/decidim.barcelona&sa=D&ust=1526042251888000[Check out the code here on GitHub].

*How can I participate in Platformname?*

Get informed

* Consult the active participatory processes.
* Browse through the proposals made by other citizens
* Access the face-to-face meetings' data and documents and the discussions and debates held there.
* Search contents of interest to you, by district, subject matter and tags.

Take part

* Make new proposals.
* Offer arguments in favour or against, or your general thoughts.
* Share the proposals on social media.

a|
Follow the existing proposals

* Follow the existing proposals: those started on the platform and those generated by face-to-face meetings.
* After the face-to-face meetings have taken place, you can follow the progress of the discussions and debates as well as the contributions generated.
* Tick a proposal of interest to you and follow its entire progress, from the comments made by others to the final documents.

*What are...?*

*Participatory processes*

*#Platformname#* activities that involve citizens and which are carried out in several stages: information, diagnosis, contributions, decisions, results and evaluation of the proposals.

*Assemblies*

Permanent participatory channels and bodies.

*Face-to-face meetings:*

Meetings and work sessions for contributing to active participatory processes.

*Surveys*

Questionnaire for providing information and sharing your opinion.

*Discussions and debates*

Digital spaces for getting informed and deciding on the proposals in the processes that have this function enabled.

*Proposals*

Contributions you can make as a user. In some cases you will be able to receive votes from other users. Some of them will have a decision-taking function and others a merely consultative function. Each process will have its own characteristic rules.

*Comments*

Contributions you can make as a user in response to a proposal or discussion and debate.

*My residency verification doesn't work.*

Check the following possibilities:

* Have you entered your national ID number or document without spaces between the digits, including the final letter?
* Are you sure you are a registered resident in the municipality of #Name of the Municipality/ Organization#? (The municipality is geographically smaller than the Barcelona Metropolitan Area and the Province of Barcelona)
* There may be a problem with your data in the residency register. Consult your nearest CITIZEN HELP AND INFORMATION OFFICE and confirm that your registration information is correct.

If all the above steps do not solve the problem, email us at #Email# or come to the face-to-face discussions and debates for each process.

*I am not a registered resident in #Name of the Municipality/ Organization#; why can't I vote for the proposals?*

Only registered residents in #Name of the Municipality/ Organization# are allowed to vote in processes where proposals can be voted on. When it comes to questions that affect decisions to be taken that are specific to the city, it is the city’s residents who need to take part in such decision-taking.

It is true that there are people not registered #Name of the Municipality/ Organization# residents who may still be affected by these decisions, but the Register is the broadest available census that we have in #Name of the Municipality/ Organization#: it allows us to reach the maximum number of people while also guaranteeing that the participatory process is secure. On the other hand, not all the processes launched from the platform require their participants to be registered residents in the city.

*I am not a registered #Name of the Municipality/ Organization# resident. Can I participate?*

Yes, you can take part even when you are not a registered resident. You can take part in several enabled processes, in face-to-face discussions and debates, and you can launch a proposal, without having to be a registered resident. It is only in some processes that voting for proposals is limited to registered residents, just as only registered residents can vote at municipal elections.

*Why do I have to verify my account?*

You need a user account to use the platform. You can do more or fewer things depending on the degree of verification:

* If you register with the website through an email address without providing any further information (so the verification process is not carried out), you will be able to comment on and debate proposals.
* If after registering, you have carried out the basic verification, i.e. you have verified your residence through the platform (more info at "How do I create and verify my account?"), you can vote for proposals in processes that are feasible (in certain processes).
* You can always take part in person and at any of the face-to-face meetings there are for each participatory process. Contributions that are made face to face will be collected, published and accessible to the platform.

*Do I need a mobile phone or access to internet to take part?*

No. You can carry out any action relating to the proposals - whether for creating, supporting, voting for or getting informed about them - face to face at any of the discussions and debates that are held. You can also create a completely verified user account if you wish to use the platform.

*How do I create and verify my account?*

The first step is to create an account. Create the account and fill in the information you are asked for. You are required to tick the box stating that you accept our user terms and conditions. On creating a new account, an email will be sent to the address you have specified, and you will have to click on the link it contains (the "Confirm my account" link) to complete the creation of the account.

Once your basic account has been created and you have logged in using your email and password, the system will give you the option of carrying out a basic verification. To do this, click on the "My account" link on the top right and then click on the "Verify my account" button.

Some processes, where necessary, will also require you to enter your residency data, to verify you are a registered resident in #Name of the Municipality/ Organization# (it is important to enter the document number along with the letter and your date of birth, and tick the box stating you accept access to the Municipal Register). If your data is correct, your account will allow you to support the proposals.

*I've forgotten my password and my account doesn't work. What can I do?*

You can request a new password, which will be sent to your email address. If the above solution does not work, you can email us at #Email#, and we will solve the problem associated with your account. Processes that include face-to-face meetings are open to you to attend and take part in, without the need for you to register with the platform.

*How can I change my email address, my user name, my password, unsubscribe or activate/deactivate the notifications that are sent to email address?*

Click on the "Enter" link, enter your email address and password, and click on the "Enter" button. Once you have done so, click on the "My account" link, where you will find all the options, allowing you to change your email address or user name, unsubscribe, or activate/deactivate notifications. Once you have made the appropriate changes, make sure you click on the "Save changes" button.

*I am unable to create my account correctly.*

Review the section "My residency verification doesn't work", in case the problem lies in this step; generally speaking, this is the most frequent problem. If this does not solve your problem, review the section "How to create and verify my account", to ensure that your are following the steps correctly. If the problem persists, email us at #Email#, and you will be given assistance.
|===

[[h.mqwt6we7yoz]]
[[h.mkf6otb3mhlh]]
== Terms and conditions of use

[[t.0c2d2bc083254e4010a82a1ac81ebd7f18f135ee]][[t.1]]

[width="100%",cols="100%",]
|===
|_Terms and conditions of use (EN)_
a|
Legal aspects and conditions of use for the #Platformname# participatory platform at #Name of the Municipality/ Organization# City Council.

(the ones that the legal services recommend you. You can use the https://www.google.com/url?q=https://decidim.barcelona/pages/terms-and-conditions&sa=D&ust=1526042251902000[Decidim.Barcelona terms and conditions of use] as a model).
|===

[[h.3oy7u29]]
== How the platform works

[[t.44b67a895959076674b8c3aa044e22bbd448f440]][[t.2]]

[width="100%",cols="100%",]
|===
|_Accessibility (EN)_
a|
This refers to the webpage's design and contents, which have to be accessible (without any visual or technological obstacles and for the largest number of users possible), and to standard regulations (WAI, Web Accessibility Initiative).

Decidim.Barcelona example https://www.google.com/url?q=https://www.decidim.barcelona/pages/accessibility&sa=D&ust=1526042251903000[Accessibility].
|===
