= Links de mídia

As conferências podem ter uma seção chamada "Mídia e links". Ele mostra uma lista de arquivos de mídia e links associados à conferência.

Os arquivos de mídia são os arquivos das seções xref:admin:spaces/conferences/attachments.adoc[attachments].
Os links de mídia são definidos em uma seção no painel de administração da conferência.

imagem:espaçaces/conferências/media_links_frontend.png[Conferências de links media (frontend)]

== Criar um novo link de mídia

imagem:espaçaces/conferências/media_links_backend.png[Conferências links de mídia]

Para criar um novo link de mídia de uma conferência:

. Entrar como administrador
. Ir para a seção de conferências na barra lateral
. Clique na ação Editar da conferência
. Clique no link "Links de Mídia" na barra lateral
. Clique no botão "Novo link de mídia"
. Preencha o formulário

imagem:espaçaces/conferências/new_media_link.png[Crie um novo link de mídia de conferência]


.Novo formulário de link de mídia
|===
|Campo |tipo |Descrição:

|Título
|Obrigatório
|O título do link

|Vincular
|Obrigatório
|URL do link

|Encontro
|Obrigatório
|Data de publicação do link

|Peso
|Opcional
|Que ordem terá em relação aos outros laços. Ter um número menor significa uma prioridade mais alta. Por exemplo, se você tiver dois links, "Link a" com peso "10" e "Link b" com peso "0", depois "Link b" será o primeiro quando fizer o pedido.
|===