= Components
:page-partial:

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::{partialsdir}/README.adoc[tag=metadata]

Decidim’s components are basic participatory mechanisms that are activated and configured for the various participatory spaces or subspaces (stages of a process, the work groups of a body, etc.).

== Proposals

Proposals are Decidim's most important component. Proposals can be defined as any element of a strategic plan, a regulation, an investment plan, a change in legislation or any other minimum decision unit. Proposals may be made by any of the following *types of creators*: by the very organisation managing the platform (e.g. a local authority); by registered participants; they may originate from a meeting as a result of a discussion or collective deliberation or may be generated by an assembly or body or by an organisation registered with the platform. They may also **be created directly or collaboratively **and be subject to *amends*.

Proposals are defined by one or more authors, a title, a text content and a category. They may also include *images*, **geo-location **and *accompanying files*.

Once a proposal has been published it may be *moderated* (if someone labels it as such and defines the reason for moderating) and it can also be *withdrawn* by author/s themselves.

Proposals in the *administration* panel can *be ordered* under various criteria, can be commented on internally (without these observations being seen by the public), can be *downloaded* in JSON or CSV format (compatible with spreadsheet software), can be *recategorised* or *moved* to different spaces. In addition, proposals may be *accepted*, *rejected* or kept in an *evaluating* state.

Other features associated with proposals include:

* *Version control*: this makes it possible to keep a record of all the changes made to a proposal, as well as code-generation to verify the proposal’s integrity.
* *Detecting similarities*: This allows anyone making a new proposal to find similar ones previously made on the platform, thereby avoiding duplications.
* *Connections between proposals*: proposals made can be connected to one another using links in the comments section, showing related proposals as cards and giving notifications on the existence of a new connection.
* *Support proposal*: participants can provide support for proposals.
* *Endorsement of proposals*: participants and collectives can endorse proposals and such public endorsement will be shown within the proposal, followers of the endorsers will be notified that the followed endorsed the proposal.
* *Modification and withdrawal of proposals*: a proposal’s author may modify and/or withdraw it before the support stage opens.
* *Amends*: any participant can edit a proposal’s text and a sub-proposal will be created in amendment mode (as Pull Request in Github). This sub-proposal may gather endorsements and supports. Besides, the proposal’s author may accept or reject the amendment (or sub-proposal). Where a sub-proposal is rejected, its author may convert it into an official proposal.
* *Proposal creation wizard*: While a proposal is being created, the participant is accompanied through the process, which is divided into different steps, with contextual help and previews before the proposal is published.
* *Collaborative draft for proposals*: Decidim permits collaboration and co-creation over proposals. It incorporates the following features:
** Creating rough drafts with numerous authors.
** The listing of collaborative drafts
** Comments in drafts
** Asking for help from and accepting the help of other collaborators


== Participatory texts

Participatory texts are defined as an ordered collection of proposals that make up a document with complete text. Participation in the text stems from interaction with the proposals that form it. This component basically allows three operations:

* *Breaking down a text document into ordered proposals* from a document in ODT, XDOC, MarkDown and HTML formats. If the text is structured in sections and subsections, ordered proposals will be created from the lower level subsection; if the text is not structured, a proposal will be created for each paragraph of text. The interface allows proposals to be re-edited, merged, separated, given titles, etc.
* *Composition of proposals in a unified text*: based on a series of proposals, these may be ordered and generate a unified and downloadable text.
* *Viewing and interacting* with documents composed of proposals: A collection of proposals will be shown as a unified text and may be amended or comments can be added in the margin.

== Results

Results are proposals (or amendments to proposals) which have ended up being the result of a decision taken in Decidim, whether directly (as a consequence of applying a voting system) or brought about by meetings, assemblies or the expert or political team in charge of a decision area through the platform’s management.

The results component allows *official responses* to be managed for all the proposals made: with the reason for rejecting or accepting the proposal and the result in which the proposal has been accepted.

Results collect *metadata on the traceability* of the proposals incorporated into the result, as well as the meetings where they were discussed and debated or created (by those attending these meetings) and the endorsements received.

== Accountability: monitoring results

The result-monitoring component enables *results to be turned into projects* or allows them to be broken down into projects or sub-projects. Each of these projects can be described in further detail and allows *the implementation status to be defined*, in sections which range from 0% implementation to 100%. The monitoring component also enables people visiting the platform to *view the level of implementation* (comprehensive, by category and/or subcategory), of the results and projects. Results, projects and statuses can be updated through a CVS, or manually by the administration interface.

== Support/votes and endorsements

Participants can endorse proposals. Such endorsements can be interpreted as votes, signatures, endorsements or in any other format that demonstrates a positive agreement in accordance with the political will itself.

There are *several support/voting and management systems* for this in Decidim. The simplest way is by activating endorsements, so that participants can issue a single endorsement for each proposal they wish, without any limit to the number of proposals that can be voted for. Alternatively, the number of votes can be limited (e.g. 10 per participant).

From the administration panel it is possible to configure the *display settings for the voting results* either during or solely after the voting period.

There is a *special form used to vote for participatory budgets* which allows participants to vote by "spending" an amount equivalent to the budget in question among the proposed projects. The number of votes is limited here by the selected projects’ accumulated spending amount.

== Comments

Comments are a special component generally associated with another component (proposals, discussions and debates, results, meetings etc.) to enable a deliberative process on an issue or proposal.

Decidim’s comments system has been designed to encourage deliberation. First-level comments, with respect to the discussion's subject matter, can be classed as: *In favour, against or neutral*. Comments can be *embedded* in subsection commentary threads and *voted on*. Decidim allows *observations to be ranked* by those in favour or against, in chronological order and by number of votes in favour.

== Informative pages

This is a page with html content and a title that appears in the inner menu of the participatory spaces. It is possible to embed images, videos and rich text here.

== Discussions and debates

Discussions and debates can be opened on questions and specific issues established by administrators or participants.

== Surveys

The surveys component allows to design and conduct surveys and to mappe out
the results, processed and displayed for surveys that can be carried out in various participatory spaces.

* *Survey configuration tool*: allows administrators to create questions and answers (open, test types, multiple selection etc.) and launch the survey, as well as download the responses in CSV format.
* *Survey interface for participants*: allows participants to respond to survey questions.

== In-person meetings

This component enables users to convene meetings, *add them to a calendar with geo-location*, upload *meeting minutes*, *debate*, create *proposals associated* with meetings (stating the type of collective endorsement for the proposal), record the *number* of participants, upload *photos* of the meeting and *categorise* the meeting within a space.

The configuration *settings* for meetings include the following *basic fields*: Title; description; address; location; Location hints; start and end time; scope; category and maximum seating capacity.

It also includes the following *advanced fields*: nature (public, open, closed); organiser group; existence of reconciliation space; adaptation to people with functional diversity; existence of simultaneous translation; type of meeting (informative, creative, deliberative, decision-making, evaluative, account giving, etc.).

Meetings relating to a participatory space (a specific process or an assembly) can be shown on a *map* and be *ordered by date or category*. Besides, all the meetings can be shown in *calendar mode*, with the possibility of exporting them to a mobile phone calendar or other apps.

Some of the meeting component’s advanced features include:

* *Registration and attendance system*:
** This allows to manage the *type of registration* (open and automatic, closed and accessible only to certain types of participants, etc.), to establish the **number of places **available for attendees, to reserve a place, to do *manual registrations*, sent out *Invitations*, to define the *conditions* that need to be accepted in order to be able to attend the meeting (e.g. image rights release), and *registering the attendance* of participants.
** It allows participants *to register* for a meeting, request *a family reconciliation service* (playroom, childcare space) and to obtain an *accreditation code* for attending at a meeting.
** Those registered who have attended a meeting will have *special access* enabling them to evaluate the meeting or make comments, etc.
** Participants or administrators will be able to receive *notifications* on registration-period openings, the number of places remaining for registrations, reminders of meetings, and the publication of minutes.
* *Managing agendas*: allows to define the duration of meetings, to create agenda’s items and sub-items, title, content, and estimated duration. Participants can propose agenda items.
* System for *drafting, publishing and validating meeting minutes* [IMPORTANT NOTE:This is currently implemented differently]:
** Minutes can be uploaded in video, audio or text format.
** Minutes in text mode are associated with a *collaborative writing board* integrated into Decidim.
** Minutes go through 4 *stages of preparation*: 1. Collaborative writing during the meeting; 2. Preparing the official draft of the minutes; 3. Draft-amendment stage; 4. Publication and final validation of the minutes.
** Minutes can be *commented on* using the comments component.
** *Accompanying documents* may also be added to the minutes.
* *Auto-convening*: verified participants will be able to convene meetings directly through the platform , with support from a certain number of other participants, the meeting will be publicly activated and convening participants will have access to the administration panel [IMPORTANT: not implemented yet]
* *Displaying and exporting meetings*: meetings can be displayed in map mode (for spaces or generally on the platform) or in calendar mode, and can be exported to agenda and calendar managers (in iCalendar format).

== Conferences

Conferences are defined as a series of meetings having several specific features (interactive and downloadable programme, registration system, system for generating certificates of attendance and/or diplomas).

Decidim has a configuration and conference-page generator, which enables the creation of an *internal website for holding conferences* relating to a participatory process or another participatory space.

Configuration settings include:

* The option to generate an *interactive programme* on the event (where there are guest speakers, it will include their name, position, organisation, a small biography and links to other websites).
* Email *invitations*.
* *Automatic diploma creation* for those who request it, through a support panel that an administrator can verify.
* Links to the event *video and materials* platforms in the programme and documents.
* Automatic links to digital-media websites covering the event.
* The ability to following events through *social networks* (e.g. by incorporating a Twitter feed).

== Blogs

Blogs are a component that allow *news items* to be created and displayed chronologically. Blog entries are another type of content and have to be associated with a participatory space. Blog entries relate to the classification system of the platform’s content. *Comments associated* with blog entries will be treated like the platform’s other comments, as described above.

== Newsletter

Decidim has a function which enables a user to send a *newsletter* (email) to everyone registered with the platform who has agreed, under the terms and conditions of use, to receiving this information newsletter email. Personalised emails are sent out addressed directly to the name of the user in the language chosen by the user by default.

Participants will automatically and directly be able to *unsubscribe* through the email itself by clicking on a link in it and it will also be possible to *track the number of visits* generated by the newsletter.

== Search engine

*The search engine* allows participants to perform searches across all of the platform’s indexable content, both generally and specifically, by searching within a specific participatory process or inside its components (proposals, results, etc.), through advanced searches.

*Pages that can be browsed and filtered from search results* show contents according to their type and ordered by the priority they have been defined under (e.g. Showing first the terms found inside assemblies and later the participatory processes).

== Sortitions

This component makes possible to select randomly a number of proposals among a set of proposals (or a category of proposals within a set) maximizing guarantees of randomness and avoiding manipulation of results by the administrator.
