= Participatory spaces
:page-partial:

Participatory spaces define the main participatory channels. They are displayed in the platform's main upper menu.

The basic logic behind Decidim's structure is that *components work together in the participatory spaces*. There are different types of spaces (initiatives, processes, consultations and assemblies) and various instances within each type (a process for an election and another for participatory budgets, council body for neighbourhoods and another for workers, an initiative to call for a change in legislation and another for something to be included in a plenary meeting agenda, etc.).

== Processes

Participatory processes require a general *configuration* form with the following fields: Title or name of the process; short name for URL; hash tag (used as a reference for communications on social networks); short description; long description; home page image; banner image; date of start and finish; field; promoter group (responsible for the participatory process on a political level, may be the local authority or a group made up of the authority’s experts/politicians and associations and other organisations); who it is aimed at; goal of the participatory process and participatory structure. The participatory process allows *accompanying documents* to be added.

Participatory processes are divided into *stages* (e.g. 1. Information and convening stage; 2. diagnostics stage; 3. proposals stage; 4. prioritisation stage; 5. decision stage; 6. evaluation stage and 7. results-monitoring stage). Each stage includes the following configuration fields: title, description, start date, end date.

*Highlights of announcements or texts* may also be displayed in the processes, both on the home page and in the heading of each component (proposals, discussions and debates, etc.) Different messages can be configured depending on the particular stage of a process.

A *participatory process configuration tool* enables the simple activation and deactivation of stages and their components. Decidim's process configuration tool is one of its most powerful features, enabling total flexibility in designing participatory processes according to the various realities and forms of citizen participation.

The feature of **process groups **enables various processes to be grouped, such as by the Participatory Budgets of different districts or neighbourhoods.

Participatory processes may have one of the following *process statuses*: 0) published or unpublished; 1) open (started); 2) closed (the participatory process has ended but its results are still under way; 3) finished (both the process and its results phase are complete) and 4) future (has not yet started).

A process can be **highlighted** (which increases its visibility on the homepage).

There is also the possibility to **copy participatory processes** from the administration panel. This feature enables process models to be designed and copied so that certain details can be configured within the new processes, avoiding the need to create them from scratch.

== Assemblies

Decidim allows the **creation and configuration** of participatory or government *assemblies* (government or participatory bodies; councils; work groups, etc.) defined as structured participant groups which, whether on an individual or representative level, meet up periodically, with the authority to make proposals and decisions.

The *assemblies section* allows you to see a full list of all of the assemblies that are activated and configured from the administration panel. The basic *settings* require the following fields to be completed for each body: name; image; scope (global, territorial or sectoral); body’s function (purpose of action); type of body (government, executive, consultative / advisory, participatory, work group, commission etc.); creation date; created on the initiative of (City Council, citizens or others); duration (indefinite or fixed, in the latter case, finishing date); date of inclusion in Decidim; date of closure and reason; how it is organised (functions, powers etc.); composition; if it can be joined and how to do that; method of choosing members; type/ function of members within the body; composition of internal work groups as monitoring or advisory committees; characteristics of the body; the body's social networks (name of social network and link) and the body’s next meetings.

* *Convening meetings*: enables to send automatic meeting invitations, collaboratively create agendas, and register attendance. For a complete list of features see the "meetings" component.
* *Assembly’s characteristics*: open, public, transparent and other characteristics regarding the level of participation that the assembly allows.
* *Composition:* This enables the composition of the body to be defined in greater detail, using the profiles of participants associated with the body as well as other characteristics. A display of the body’s structure is automatically generated based on the composition of participating members:
** *Types of members*: Chair, deputy chair, secretaries, others
** *Membership origin*: by draw; direct election; representation from another assembly; government representation etc.
** *Internal work groups*: for the creation of sub-assemblies. Work groups will be able to relate to the body they belong to
** *Characteristics*: Open/closed; transparent; with various access permits.
* *Display*: allows us to view internal data about each body as well as the associations between assemblies
** *Composition*: the structure of a body is shown in the form of a circle diagram
** *Organisation charts*: allow us to view the hierarchy or network of assemblies and their associations.
* *Map and calendar*: allow us to view the location of all the assemblies on a map and calendar
* *Involvement with other spaces and components*
** *Involvement with processes*: assemblies can be promoter groups, start a process or make proposals within a process. A body’s composition may be the result of a process (for electing posts)
** *Proposals and results*: a body can generate its own proposals or results.
*** It shows how the proposal was agreed on (by consensus, majority, number of votes etc.).
** *Meetings*: assemblies will have a list of associated meetings, but some features may jump from one meeting to another, such as citizen initiatives to include an item in an agenda. Likewise, it must be possible to view minutes separately from the meeting, as they are associated directly with the body .

== Initiatives

*Initiatives*. This participatory space allows citizens to make proposals and collect the *requisite number of signatures and/or endorsements* depending on type (the various types are set out in the municipal regulations), giving rise to the start of the administrative procedure for its processing and citizen monitoring.

Initiatives operate as follows:

* Any person or citizen association can make a citizen-initiative proposal. There are *several types of initiatives* with various numbers of endorsements/signatures required for their processing (these are all configurable). From the initiative-creation page, a description of each of the methods, the number of signatures required and examples (e.g. explanatory videos) can be viewed.
* To avoid duplicates, once an initiative has been created, the system will present suggestions for **similar initiatives** before continuing with the following step. Once similar proposals have been ruled out, the specific form will be shown for each type of initiative, along with the minimum number of endorsements required. The creator then has an URL at their disposal which can be used to invite others to join in and endorse the initiative. A map is also displayed showing the locations of meeting points to collect signatures should there be any.
* Once the the initiative has been created, the initiative will move to a **technical moderation and validation** stage, where the City Council’s staff can respond in various ways (by approving it, rejecting it or suggesting amendments).
* Initiatives can be monitored and **notifications received on updated** statuses, in addition to which their individual promoter or group can periodically send information newsletters to other uses of the platform who have opted to follow the initiative.
* On reaching the specified end date, an initiative can have two possible states:
** *Rejected*: where it fails to reach the minimum number of signatures, a message will be shown stating "does not meet the number of signatures required" and the initiative's creator will be notified.
** *Accepted*: where it has achieved a sufficient number of signatures or endorsements it will be accepted and the corresponding procedure will start.

== Consultations

Consultations (a voting procedure where all of the organisation’s participants are called to vote on specific questions), allows participants **to find out about current or prospective consultations**, *discuss and debate* the consultation’s subject area and *monitor* the results. It also provides a *gateway to an e-voting system* which is external to Decidim but integrated in the interface in order to manage and verify identities.
