= Participatory spaces
:page-partial:

There are different types of Participatory Spaces: *Initiatives*, *Processes*, *Consultations* and *Assemblies*. 

Specific examples of each of these include: a citizen initiative for directly changing a regulation (_Initiative_); a general assembly or workers’ council (_Assembly_); a participatory budgeting, strategic planning, or electoral process (_Processes_); a referendum or a call to vote “Yes” or “No” to change the name of an organization (_Consultation_).

A *Participatory Space* and its contents can be (independently) assigned a *Scope*. Scopes are defined for the whole platform, and they can be thematic or territorial (for example, an assembly can be assigned to a specific theme or subject, like "ecology", and to a specific territory, like a district within a city). 

Content within a space-instance can be assigned to a *Category* or sub-category (e.g. topics) that are specific for such a space-instance. For example, the categories "sport facilities", "parks" and "schools" can be created for a participatory budgeting process, and proposals will be assigned to these categories. 

== Initiatives
*Initiatives* is a special kind of space by which members of an organization can trigger actions that are generally restricted to elected bodies or platform administrators, by collecting (digital) signatures. 
The organization can define the types of initiatives and set up the number of signatures that are required to trigger the expected result (e.g. to call for a consultation).

Initiatives operate as follows:

* A person or citizen association makes a citizen-initiative proposal.
* The system presents suggestions for similar initiatives, for avoiding duplicates. 
* Once similar proposals have been ruled out, the new Initiative is created. The creator can define the minimum number of endorsements required for this Initiative. If any location to collect signatures is defined, a map is displayed showing it. The Initiative's URL can be used to invite others to join in and endorse it. 
* The initiative moves to a **technical moderation and validation** stage, where the organization’s staff can respond in various ways (by approving it, rejecting it or suggesting amendments).
* Initiatives can be monitored through notifications and status updates. In addition to this, their individual promoter or group can periodically send information newsletters to other Participants of the platform who have opted to follow the initiative.
* On reaching the specified end date, an initiative can have two possible states:
** *Rejected*: where it fails to reach the minimum number of signatures, a message will be shown stating "It does not meet the number of signatures required" and the initiative's creator will be notified.
** *Accepted*: where it has achieved a sufficient number of signatures or endorsements it will be accepted and the corresponding procedure will start.

== Processes

Participatory processes may have one of the following *process statuses*: 

  0) published or unpublished
  1) open (started)
  2) closed (the participatory process has ended but its results are still under way
  3) finished (both the process and its results phase are complete)
  4) future (has not yet started)

Participatory Processes can be divided into different *stages* (e.g. 1. Information and convening stage; 2. diagnostics stage; 3. proposals stage; 4. prioritisation stage; 5. decision stage; 6. evaluation stage and 7. results-monitoring stage). Each stage can display notes associated to it to the Participants.

The feature of **process groups **enables various processes to be grouped, such as by the Participatory Budgets of different districts or neighbourhoods.

A process can be **highlighted** (which increases its visibility on the homepage).

There is also the possibility to **copy participatory processes** from the administration panel. This feature enables process models to be designed and copied so that certain details can be configured within the new processes, avoiding the need to create them from scratch.

== Consultations
*Consultations* is a space that makes it possible to coordinate referendums, trigger discussions and debates, get voting results published; it can be connected to a secure e-voting system. 

== Assemblies
*Assemblies* is a space that offers the possibility of setting decision-making bodies or groups that meet up periodically, detailing their composition, listing and geolocating their meetings, and allowing to take part in them (for instance: attending if the seating capacity and nature of the assembly so permits, adding items to the agenda, or commenting on the proposals and decisions taken by that body). 
