= Participants

:page-partial:

*Participants* of Decidim can be grouped into three different categories:

* *Visitors* have access to all of the platform's content without having to sign up or provide any information.
* *Registered* participants can submit proposals and comments, sign-up for meetings, endorse content, follow other Participants and receive notifications, mentions and private messages.
Users may register *directly* on the platform or through gateways of other *social networks* (Facebook, Twitter or Google+). To register directly, users will need to associate a email account and a password to the user-account.
 Registered participants can also have their account officialized (meaning their username is accompanied by a special symbol indicating they really are who they claim they are on their profile).
* *Verified* participants can make decisions. Decidim offers different ways to carry out this verification.

Administrators can *manage permissions* for *Registered* users and *Verified* users selectively. For example, _proposal creation_ can be activated for both Registered and Verified users but _supports to proposals_ only for Verified users.

== Public registration of administrative activity

The manual verification of participants, as well as other administrative actions can create vulnerability or may enable the administrators to use the platform in an abusive manner. To avoid it, Decidim includes a *public register of administrative activities* so these actions can be publicly and transparently audited.

== User profile and personal settings

There is a **user-profile page **where participants can make **changes to their data **(such as email account, password etc.), upload and enable an *avatar* image, set notifications or delete their account.

The user-profile page also allows participants to add *additional information* to include interests and skills, voluntarily and by selecting the level of visibility of that information. This allows personal notifications to be sent and participants can be matched with others for collaborations.

== Monitoring and notifications

Participants receive *automated notifications* regarding the content they have created: responses to comments and comments on their proposals, as well as the results of their proposals (whether accepted or rejected).

Besides automated notifications, participants can decide to **follow any element** of the system (other proposals, results, processes, assemblies, initiatives, groups or users etc.), and receive notifications.

== Communication among participants

**Instant messages **can be sent to participants through the platform, who will receive an email notification.

*Mentions* can also be added (in the comments section) to any registered user and a notification will be automatically sent.

== User groups

Participants can register with the platform as members of one or several organisations/collectives. Once the organisation and membership status have been verified, participants can carry out actions (make proposals or submit comments, etc.), with their user or with the organisation name.

User groups can also manage user permissions and administration roles assigned to groups, as well as private debate spaces or share information among group users, for example, who attended an in-person meeting. [Feature currently missing]

== Engagement

Decidim has a series of features geared to _gamifying_ the platform, to *attract and keep a growing number of participants interested*, as well as to promote practices that boost democratic quality and collective intelligence in participation [the gamification system is expected for 2018Q2-3, AjB-Lote1].

The gamification system includes two modes, one centred on users and the other on proposals.

* The **user-centred **mode incorporates a *points system* based on several criteria (degree of detail of its user profile, number of invitations to others on the platform, number of proposals made and commented on, number of comments, number of endorsements obtained, number of followers, etc.)

The combination of these and other indicators is used for generating gamification routes for each user and defining threads such as: most participatory person in the district, leadership in discussions and debates, etc.

* Gamification *centred on proposals/initiatives* allows promoters, signatories and followers to boost interaction with them by incorporating several *metrics* (number of times that the proposal is shared in social networks, degree of controversy (number of positive and negative comments), quality of deliberation (depth of observation tree), number of hits received, etc.