= Anexos

Anexos permitem que um administrador faça upload de arquivos estáticos para um espaço.

Quando um espaço é lançado, é importante fornecer aos cidadãos toda a informação possível sobre eles, para que possam participar com conhecimentos. É por isso que é útil adicionar ficheiros (Attachments) com as informações consideradas relevantes.

Opcionalmente, esses documentos podem ser agrupados em *Pastas*. Por exemplo, para um processo participativo de remodelação de um quadrado, poderiam ser criadas pastas com informação sobre possíveis usos, com planos, com informações económicas, etc.

Eles podem ser encontrados na página inicial do espaço:

imagem:spaces/attachments_folder.png[Veja os anexos da pasta na interface pública]

imagem:spaces/anexos.png[Veja os anexos na interface pública]

== Criar um novo anexo

imagem:spaces/attachments_admin.png[Veja os anexos na interface do administrador]

Para criar um novo anexo de um espaço:

. Entrar como administrador
. Ir para a seção de espaço na barra lateral
. Clique na ação Editar Espaço
. Clique no link dos anexos na barra lateral
. Clique no botão "Novo anexo"

imagem:spaces/attachments_new_form.png[Crie um novo formulário de anexo]


.Criar anexo
|===
|Campo |tipo |Descrição:

|Nome de imagem ou anexo
|Obrigatório
|Qual é o título para este anexo.

|Peso
|Opcional
|Que ordem terá em relação aos outros anexos. Ter um número menor significa uma prioridade mais alta. Por exemplo, se você tem duas categorias, "Anexo" com peso "10" e "Anexo b" com peso "0", em seguida "Anexo b" será o primeiro durante a ordenação.

|Descrição:
|Obrigatório
|Uma longa descrição explicando o que é esse arquivo.

|pasta
|Opcional
|Qual pasta pertence a este anexo.

|Arquivo
|Obrigatório
|Enviar o arquivo. Guia para o arquivo: Tem que ser uma imagem ou um documento. Para imagens, use preferencialmente imagens de paisagem, o serviço
cultiva a imagem. Para arquivos CSV, o separador entre colunas deve ser uma vírgula (","). Tamanho máximo do arquivo: 10MB. Extensões
permitidas dependem da configuração do seu servidor.
|===

== Criar nova pasta

imagem:spaces/attachments_new_folder_form.png[Crie uma nova pasta para formulário de anexos]


.Criar pasta
|===
|Campo |tipo |Descrição:

|Nome:
|Obrigatório
|Nome da pasta

|Peso
|Opcional
|Qual será a ordem em relação às outras pastas. Ter um número menor significa uma prioridade mais alta. Por exemplo, se você tem duas pastas, "Pasta a" com peso "10" e "Pasta b" com peso "0", em seguida "Pasta b" será o primeiro na ordenação.

|Descrição:
|Obrigatório
|Uma longa descrição explicando sobre o que é essa pasta.
|===