= categorias

Categorias (e subcategorias) são utilizadas para classificar os recursos dentro de um espaço.

Um administrador pode defini-los, pode ser atribuído ao criar recursos, e então os participantes podem filtrar
recursos diferentes por essas categorias. Por exemplo, podem ser criadas em propostas, reuniões e debates.

Como um exemplo desse mecanismo em ação, você pode vê-lo em https://meta.decidim.org/processes/roadmap/f/122/[Propor novas funcionalidades para o software decidim]:

. Os administradores definiram as categorias no processo.
. Os usuários podem criar propostas que têm uma categoria.
. Os participantes podem filtrar por estas categorias e navegar entre todas as propostas.

imagem:spaces/categories_sidebar.png[Filtrar categorias nas propostas]

imagem:spaces/categories_form.png[Selecione uma categoria quando criar uma proposta]

NOTE: Uma vez que uma categoria esteja em uso, ela não pode ser removida, pois há recursos que a estão usando.

Decidim tem outras maneiras de classificar recursos, por exemplo xref:admin:scopes.adoc[Scopes] and xref:admin:features/hashtags.adoc[Hashtags].
A principal diferença é que as Categorias podem ser definidas em um determinado espaço, Âmbitos são globais para todas as plataformas, e Hashtags
são definidas pelos participantes.

As categorias podem ser aninhadas, o que significa que uma categoria pode ter subcategorias.

== Criar uma nova categoria

Para configurar uma nova categoria, vá para o painel de administração do espaço e clique na guia "Categorias".

imagem:spaces/categories.png[Ver categorias na página de administração do espaço]

Em seguida, clique em "Adicionar categoria" e preencha o formulário.

imagem:spaces/categories_new_form.png[Crie um novo formulário de categoria]


.Criar categoria
|===
|Campo |tipo |Descrição:

|Nome:
|Obrigatório
|Qual é o nome para esta categoria.

|Peso
|Opcional
|Qual será a ordem em relação às outras categorias. Ter um número menor significa uma prioridade mais alta. Por exemplo, se você tem duas categorias, "Categoria a" com peso "10" e "Categoria b" com peso "0", em seguida "Categoria b" será o primeiro na ordenação.

|Descrição:
|Obrigatório
|Uma longa descrição explicando sobre o que é esta categoria.

|Antecessor
|Opcional
|Qual é a categoria pai.
|===