= Participantes privados

Há casos em que você quer ter um recenseamento fechado dos participantes em um espaço. Por exemplo, isso pode ser um espaço
para um pequeno grupo de pessoas, ou os membros de uma comissão dentro de uma grande organização. For these cases you can
use the private participants feature.

imagem:spaces/private_participants.png[Lista privada de participantes]

Convidar participantes privados do espaço:

. Entrar como administrador
. Ir para a seção do espaço na barra lateral
. Clique na ação Editar Espaço
. Clique no link "Participantes Privados" na barra lateral
. Clique nos botões "Novo espaço participativo de usuário privado" ou "Importar via CSV"

== Novo espaço participativo de usuário privado

imagem:espaços/private_participants_new_form.png[Novo formulário de participante privado]


.Novo espaço participativo formulário privado de usuário
|===
|Campo |tipo |Descrição:

|Nome:
|Obrigatório
|Qual é o nome do novo participante.

|e-mail
|Obrigatório
|Qual é o e-mail do novo participante.
|===

== Importar via CSV

imagem:spaces/private_participants_csv_import.png[Importar participantes privados via CSV]

Este formulário permite que você importe em massa os participantes de um espaço.

Deve ter duas colunas com e-mail na primeira coluna do arquivo e o nome na última coluna do arquivo (e-mail, nome)
dos usuários que você deseja adicionar ao espaço participativo. Algumas dicas:

* O arquivo não deve ter cabeçalhos. Isso significa que você não precisa adicionar uma coluna que diz "email, nome"
* Você deve evitar o uso de caracteres inválidos como `<>?%&^*#@()[]=+:;"{}\├` no nome de usuário.
* O separador entre colunas deve ser uma vírgula (",")

== Ações.

Depois que os participantes forem convidados, você poderá reenviar ou excluir o convite.

imagem:espaços/private_participants_actions.png[Ações de participantes privados]

|===
|Ícone |Nome: |Definição

|imagem:action_resend_invitation.png[Reenviar convite]
|Reenviar convite
|Se o convite não foi aceito, envie-o novamente para o usuário

|imagem:action_delete.png[Excluir convite]
|Excluir convite
|Revogar o convite enviado ao usuário
|===

== Convite

When a participant was invited she'll get an email with a link for accepting the invitation:

imagem:espaços/privado_participants_email_invite.png[E-mail de um participante privado]

After clicking in this email, she'll have to fill a form for setting her password, accepting the Terms of Service and giving
her consent if she wants to receive newsletters.

imagem: spaces/private_participants_user_registration_form.png[Formulário de registro de usuário de um participante privado]