= Technical tradeoffs

== Architecture

This is not your typical Ruby on Rails Vanilla App. We've tried using http://decide.es[Consul] but we found some problems on reutilization, adaptation, modularization and configuration. You can read more about that on "https://www.gitbook.com/book/alabs/propuesta-de-cambios-en-la-arquitectura-de-consul/details[Propuesta de Cambios de Arquitectura de Consul]".

== Turbolinks

Decidim doesn't support `turbolinks` so it isn't included on our generated apps and it's removed for existing Rails applications which install the Decidim engine.

The main reason is we are injecting some scripts into the body for some individual pages and Turbolinks loads the scripts in parallel. For some libraries like http://leafletjs.com/[leaflet] it's very inconvenient because its plugins extend an existing global object.

The support of Turbolinks was dropped in https://github.com/decidim/decidim/commit/d8c7d9f63e4d75307e8f7a0360bef977fab209b6[d8c7d9f]. If you're interested in bringing turbolinks back, further discussion is welcome.
