= notificações

Nesta seção, os participantes podem escolher que tipo de notificações receberão. Por exemplo, dependendo da atividade da instalação e dos espaços, a maioria das pessoas gostaria de desativar "Tudo o que sigo "

imag:features/minha_conta/notificações_settings.png[Configurações de notificações]

Para ir para esta turma:

. Iniciar sessão como participante
. Clique no nome do usuário no cabeçalho
. Clique em "Minha conta"
. Clique em "Configurações de notificações" na barra lateral

As opções disponíveis são:

* Quero receber notificações sobre
** Minha própria atividade, como quando alguém comenta minha proposta ou me menciona
** Tudo o que eu sigo
* Enviar notificações por e-mail
** Quero receber um e-mail sempre que receber uma notificação
* Notícias
** Quero receber boletins informativos
* Receber mensagens diretas de qualquer pessoa
** Permita que qualquer pessoa me envie uma mensagem direta, mesmo que eu não a sigo
* Administradores
** Quero receber um e-mail toda vez que algo for reportado para moderação