= Authorship Criteria
include::decidim::partial$l10n.adoc[]

Contributions to the documents included in this documentation site may be of varying nature.
The different authorship levels and criteria are stated below:

[#editors]
Editors ::
Responsible for monitoring a text and its versions, corrections and structure etc., and may or may not be one of the authors.
In essence, an editor is someone who coordinates collaboration on the text.
One of the editor's responsibilities is to request and read revisions.

[#authors]
Authors ::
Strictly speaking, authors are those who have drafted the text.
The order of the authors listed reflects their contribution, with the first mentioned being the one who has written the most.
Authors must have read and revised their text in its final or previous versions, although they do not have to agree with its final form, a task that falls to the editor.

[#contributors]
Contributors ::
Two groups of contributors are considered here.
On the one hand, the document's academic revisers (where they have made a considerable contribution) and, on the other, external collaborators whose contributions have been valuable and integrated in parts of the text included in the document.
It is up to the editor and other authors to decide who is a contributor or an author, although the former is in any case meant to contribute less than the latter.
As a general rule, a person who has written under 10% of the text ought to be considered a contributor rather than an author.
By the same token, being a contributor means having written at least two or three paragraphs.

[#participants]
Participants ::
This is someone who has not contributed any specific text to the document but who has made valuable contributions such as observations about the document or provided valuable criteria, references or elements of discussion.

[#proofreaders]
Proofreaders ::
Their work includes carefully reading an entire text, correcting errors and suggesting improvements.
Such work is generally commissioned (requested from a person regarded as competent in the field), although it is possible for someone to contribute by proofreading a text that has not been explicitly requested.
In such cases, the depth and quality of the proofreading process may qualify a person to be considered as a proofreader.

This division and specification of authorship levels has been directly copied from the criteria established under http://floksociety.org/[the FLOK Society - Buen conocer] (see http://book.floksociety.org/ec/[Barandiaran et al. 2015], pp. 38-39).
