= Criteris d'autoria
include::translations::partial$attributes.adoc[]

Les contribucions als documents inclosos en aquest site de documentació poden ser de diversa naturalesa.
Els diferents nivells i criteris d'autoria s'expliquen a continuació:

[#editors]
Editor/a ::
S'encarrega del monitoratge del text, les seves versions, correccions, estructuració, etcètera.
Pot coincidir o no amb algun dels autors.
Es tracta, en definitiva, d'un coordinador de la col·laboració del text.
És funció de l'editor sol·licitar les revisions i llegir-les.

[#authors]
Autor/a ::
Són autors els qui pròpiament han redactat el text.
L'ordre dels autors en reflecteix la contribució; el primer nom és el de qui més ha escrit.
L’autor haurà llegit i revisat el text en la seva versió final o en versions anteriors, però no cal que estigui d'acord amb la configuració final del text.
Aquesta tasca queda en mans de l'editor.

[#contributors]
Contribuïdor/a ::
Aquí poden considerar-se dos grups de contribuïdors.
D'una banda, les persones encarregades de la revisió acadèmica del document (en cas que la seva contribució sigui considerable) i, de l’altra, col·laboradors externs la contribució dels quals hagi estat valuosa i s'hagi consolidat en parts de text incloses al document.
La diferència entre contribuïdor i autor queda en mans de l'editor o de la resta d'autors però, en tot cas, la contribució ha de ser inferior a la de la resta d'autors.
Com a regla general, si un autor ha escrit menys del 10% del text s'hauria de considerar contribuïdor.
Al seu torn, ser contribuïdor requereix almenys haver escrit dos o tres paràgrafs.

[#participants]
Participant ::
Es tracta d'una persona que, sense haver contribuït amb una part de text específica al document, ha fet contribucions de valor, com ara comentaris pertinents, o ha proporcionat criteris, referències o elements de discussió valuosos.

[#proofreaders]
Revisor/a ::
Aquesta tasca inclou una lectura minuciosa de tot el text, la correcció d'errors i la proposta de millores.
En general, és una feina per encàrrec (sol·licitada a una persona que es considera competent en la matèria), encara que és possible que algú contribueixi fent una revisió sense sol·licitud expressa.
En tal cas, la profunditat i qualitat d'aquesta es poden valorar per considerar aquesta persona revisora.

Aquesta divisió i especificació de nivells d'autoria s'ha copiat directament dels criteris establerts en el projecte http://floksociety.org/[FLOK Society - Buen conocer] (veure http://book.floksociety.org/ec/[el llibre del mateix títol, Barandiaran et al. 2015], pàgines 38-39).
