= Páginas de informações

$legacyparcial .adoc[]

Aqui oferecemos três páginas informativas que você pode usar como modelo ou reutilizar o texto destacado em amarelo pelo texto correto. Você pode encontrar os mesmos documentos em espanhol ou catalisador em seu respectivo documento de administração do Decidim.

== Informação/Perguntas Frequentes

[[t.6a4146f0a2c8ecae39afa2642bcb7f700ef842af]][[t.0]]

[width="100%", cols="100%"]
|===
|_FAQS (EN)_

a|Se você quiser participar de processos participativos e participar da sua mensagem, cadastre-se! Observe que para usar algumas das funções de certos processos (como votação e prioridade) você terá que verificar se está registrado com #Name da Municipalidade/ Organização#, seguindo um passo muito simples.

*O que é #Name da Organização Municipal?#*

Uma plataforma para a construção de um #Nome mais participativo do Município/Organização#, com uma visão compartilhada e para aprofundar a democracia participativa local.

#Platformname# é uma plataforma participativa baseada em código aberto. Os cidadãos podem ver como foi construído e podem reutilizar ou melhorá-lo. https://www.google.com/url?q=https://github.com/AjuntamentdeBarcelona/decidim.barcelona&sa=D&ust=1526042251888000[Confira o código aqui no GitHub].

*Como posso participar da Plataforma?*

Seja informado

* Consulte os processos participativos ativos.
* Navegue pelas propostas feitas por outros cidadãos
* Acesse os dados e documentos das reuniões presenciais, bem como as discussões e os debates aí realizados.
* Pesquisar conteúdo de interesse para você, por distrito, assunto e marcações.

Capturar parte

* Faça novas propostas.
* Proporciona argumentos a favor ou contra, ou as vossas ideias gerais.
* Compartilhe as propostas sobre as redes sociais.

a|Siga as propostas existentes

* Siga as propostas existentes: as iniciadas na plataforma e as geradas por reuniões presenciais.
* Depois de se terem realizado reuniões presenciais, pode-se acompanhar o andamento das discussões e debates, bem como as contribuições geradas.
* Marque uma proposta que lhe interessa e acompanhe todo o seu progresso, desde os comentários feitos por outros até aos documentos finais.

*O que são...?*

*Processos participativos*

Atividades de *#Platformname#* que envolvem os cidadãos e que são realizadas em várias etapas: informação, diagnóstico, contribuições, decisões, resultados e avaliação das propostas.

*Assemblies*

Corpos e canais participativos permanentes.

*Reuniões faciais:*

Reuniões e sessões de trabalho para contribuir para processos participativos ativos.

*Pesquisas*

Questionário para fornecer informações e compartilhar sua opinião.

*Discussões e debates*

Espaços digitais para ser informado e decidir sobre as propostas nos processos que têm essa função habilitada.

*Propostas*

Contribuições que você pode fazer como usuário. Em alguns casos, você poderá receber votos de outros usuários. Algumas delas terão uma função de tomada de decisões e outras uma função meramente consultiva. Cada processo terá as suas próprias regras características.

*Comentários*

Contribuições que você pode fazer como usuário em resposta a uma proposta ou discussão e debate.

*Minha verificação de residência não funciona.*

Verifique as seguintes possibilidades:

* Você digitou o seu número de identificação ou documento nacional sem espaços entre os dígitos, incluindo a carta final?
* Você tem certeza de que é um residente no município #Nome da Organização Municipal?format@@0 (O município é geograficamente menor do que a zona Metropolitana de Barcelona e a província de Barcelona)
* Pode haver um problema com seus dados no registro de residência. Consulte seu AJUDA DE CITIZEN mais próximo e seu OFICE DE INFORMAÇÕES e confirme que suas informações de registro estão corretas.

Se todos os passos acima não resolverem o problema, envie-nos um e-mail para #Email# ou venha para as discussões e debates presenciais de cada processo.

*Não sou um residente registrado em #Nome da Organização Municipal#; por que não posso votar a favor das propostas?*

Apenas moradores registrados em #Nome da Organização Municipal/ Pessoal # podem votar em processos onde as propostas podem ser votadas. Quando se trata de questões que afectam decisões a tomar que são específicas da cidade, São os residentes da cidade que precisam de participar nessa tomada de decisão.

É verdade que há pessoas que não estão registradas #Name dos residentes da Municipalidade/ Organização# que ainda podem ser afetadas por essas decisões, mas o Registro é o censo mais amplo disponível que temos em #Name of the Municipality/ Organization#: ele nos permite alcançar o número máximo de pessoas, garantindo ao mesmo tempo que o processo participativo é seguro. Por outro lado, nem todos os processos lançados a partir da plataforma exigem que seus participantes sejam residentes na cidade.

*Eu não sou um #Nome do residente municipality/ Organization# registrado. Posso participar?*

Sim, pode participar, mesmo quando não é um residente registado. Podem participar em vários processos habilitados, em discussões e debates presenciais. e é possível lançar uma proposta sem ter de ser um residente registado. Só em alguns processos é que a votação das propostas se limita aos residentes registados, tal como apenas os residentes registados podem votar nas eleições autárquicas.

*Por que eu tenho que verificar minha conta?*

Você precisa de uma conta de usuário para usar a plataforma. Você pode fazer mais ou menos coisas dependendo do grau de verificação:

* Se você se registrar com o site através de um endereço de e-mail sem fornecer mais informações (por isso, o processo de verificação não será realizado), Os senhores deputados poderão comentar e debater propostas.
* Se após o registo, procedeu à verificação básica, ou seja, você verificou sua residência através da plataforma (mais informações em "Como eu crio e verifico minha conta? ), você pode votar em propostas em processos que são viáveis (em certos processos).
* Você sempre pode participar pessoalmente e em qualquer das reuniões presenciais que existem para cada processo participativo. Contribuições dadas face a face serão recolhidas, publicadas e acessíveis à plataforma.

*Preciso de um celular ou de acesso à internet para participar?*

Não. Você pode realizar qualquer ação relacionada com as propostas - seja para criar, apoiar, votando a favor ou sendo informados sobre eles - face a face em qualquer das discussões e debates que se realizam. Você também pode criar uma conta de usuário completamente verificada se desejar usar a plataforma.

*Como crio e verifico minha conta?*

O primeiro passo é criar uma conta. Crie a conta e preencha as informações que você pediu. Você deve marcar a caixa que indica que você aceita nossos termos e condições do usuário. Ao criar uma nova conta, um e-mail será enviado para o endereço que você especificou, e você terá que clicar no link que ele contém (o link "Confirmar minha conta") para concluir a criação da conta.

Uma vez que sua conta básica foi criada e você entrou usando seu e-mail e senha, o sistema lhe dará a opção de realizar uma verificação básica. Para fazer isso, clique no link "Minha conta" no canto superior direito e, em seguida, clique no botão "Verificar minha conta".

Alguns processos, quando necessário, também exigirão que você insira os dados de residência, para verificar que você é um residente registrado no #Nome do Municipal/ Organização # (é importante inserir o número do documento juntamente com a letra e a data de nascimento, e marque a caixa que indica que você aceita o acesso ao Registro Municipal). Se seus dados estiverem corretos, sua conta permitirá que você apoie as propostas.

*Eu esqueci a minha senha e a minha conta não funciona. O que posso fazer? *

Você pode solicitar uma nova senha, que será enviada para o seu endereço de e-mail. Se a solução acima não funcionar, você pode nos enviar um e-mail para #Email#, e nós resolveremos o problema associado à sua conta. Processos que incluem reuniões presenciais estão abertos a você para participar e participar, sem a necessidade de você se inscrever na plataforma.

*Como posso alterar meu endereço de e-mail, meu nome de usuário, minha senha, cancelar assinatura ou ativar/desativar as notificações enviadas para o endereço de e-mail?*

Clique no link "Enter", insira seu endereço de e-mail e senha e clique no botão "Enter". Assim que você tiver feito, clique no link "Minha conta", onde você encontrará todas as opções, permitindo que você altere seu endereço de e-mail ou o nome de usuário, cancele sua inscrição ou ative as notificações. Uma vez que você tiver feito as alterações apropriadas, certifique-se de clicar no botão "Salvar alterações".

*Não consigo criar minha conta corretamente.*

Revise a seção "A verificação de minha residência não funciona" caso o problema resida nessa etapa; de um modo geral, este é o problema mais frequente. Se isso não resolver seu problema, revise a seção "Como criar e verificar minha conta", para garantir que você esteja seguindo os passos corretamente. Se o problema persistir, envie um e-mail para #Email#, e você receberá assistência.
|===

[[h.mkf6otb3mhlh]]
== Termos e condições de uso

[[t.0c2d2bc083254e4010a82a1ac81ebd7f18f135ee]][[t.1]]

[width="100%", cols="100%"]
|===
|_Termos e condições de utilização (EN)_

a|Aspectos legais e condições de uso para a plataforma participativa #Platformname# em #Nome da Municipalidade/ Organização# Cidade.

(Os serviços jurídicos recomendam a sua recomendação. Você pode usar o https://www.google.com/url?q=https://decidim.barcelona/pages/terms-and-conditions&sa=D&ust=1526042251902000[Decidim.Barcelona termos e condições de uso] como um modelo).
|===

[[h.3oy7u29]]
== Como a plataforma funciona

[[t.44b67a895959076674b8c3aa044e22bbd448f440]][[t.2]]

[width="100%", cols="100%"]
|===
|Acessibilidade (EN)_

a|Isso se refere ao design e conteúdo da página da Web, que devem ser acessíveis (sem quaisquer obstáculos visuais ou tecnológicos e pelo maior número possível de usuários), e para os regulamentos padrão (WAI, Web Accessibility Initiative).

Exemplo Decidim.Barcelona https://www.google.com/url?q=https://www.decidim.barcelona/pages/accessibility&sa=D&ust=1526042251903000[Accessibility].
|===