= Decidim's Social Contract

[NOTE]
====
You can also read Decidim's Social Contract in other languages: xref:understand:social-contract-ca.adoc[Català] - xref:understand:social-contract-es.adoc[Castellano]

If you want to translate it to your own language please https://decidim.org/contact[contact us].
====

All members and partners of the Decidim project must endorse and follow a Social Contract.

By signing this Social Contract, any individual, institution or social group of any kind commits to fulfill the principles established here when using, developing and participating in the community of Decidim.

== Free Software and open content

Decidim will always remain free and open to collaboration, without legal or technical obstacles for the use, copy and modification. To ensure this we use a set of licenses:

 - https://www.gnu.org/licenses/agpl-3.0.en.html[Affero GPLv3 license or later versions] or compatible licenses for the code of the platform, the modules, libraries and any other code that is developed or re-used for its functioning and deployment.
 - https://creativecommons.org/licenses/by-sa/4.0/legalcode[Creative Commons By-SA license] for the content (text, graphics, images, fonts, audio, video or other design elements). 
 -  http://opendatacommons.org/licenses/odbl[Open Data Commons Open Database License] for the data available through the platform, especially all data that can be collected in a systematic way through scrappers or other techniques of massive consultation. These data should be published under standardized and accessible formats (such as CSV, JSON, etc.) and, whenever possible, with tools that facilitate the analysis and visualization of data.
 
The content, data, APIs and/or any other interfaces that are deployed to interact with any type of user must follow open and interoperable standards (ex. OpenID, RSS, OStatus, etc.), always tending to maximize their integration with the most widely used open standards.


== Transparency, traceability and integrity

The content of participation will always remain transparent, traceable and integral. 

  - _Transparent_ means that all the content must be accessible and downloadable. This should never be applied to personal data or against the defense of the privacy of the people participating in the platform.

  - _Traceable_ means that it should always be possible to fully track backward (past) and forward (future) each object of participation or decision (proposal, plan, regulation, etc.) included in a process. The platform must at all times show how, why, by whom and with what guarantees a certain type of object of a participatory process was dismissed, approved or blocked.

  - _Integral_ means that the content needs to be displayed without having been manipulated. Any modification (if required) must be registered and be accessible and auditable.


== Equal opportunities, democratic quality and inclusiveness

The platform promises to ensure equal opportunities for all people, as well as for their proposals or other contributions the platform might host. 

All participatory objects (proposals, debates, etc.) should be equally viewed, discussed, commented, evaluated or treated without discrimination of any kind.

The platform must comply with accessibility standards, its use must favour the integration of online and offline participation and organizations must deploy the means for mediation and training of participants.
the unicity and democratic rights of participants must be preserved (meaning there cannot be two verified users corresponding to the same individual with democratic rights and all participants with such rights must be verifiable).


== Data confidentiality

The confidentiality and privacy of the personal data that people might provide to participate in any of the functionalities and/or possibilities of participation that the platform provides shall be guaranteed at all times. In no case shall personal data be transferred to third parties. Personal data will not be used beyond what is strictly necessary for the purposes of user registration and improvements on the usability of the platform. Whenever platform technology makes it possible, the expression of political preferences or will in decision-making processes shall remain inaccessible even for the administrator of the platform or the server/s that host it.

== Accountability and responsibility

Institutions using Decidim must commit to respond to all queries and contributions in the shortest time possible. A commitment shall also be adopted to follow-up the results of participatory processes and to respond to those demands which specifically request it. Finally, a commitment shall be taken to study the incorporation of indicators to monitor the participation processes once they are finalized, in order to systematically evaluate its implementation.

== Continuous improvement and inter-institutional collaboration

Mechanisms for periodic review and evaluation will be provided in order to facilitate the continuous improvement of the platform.

Priority will be given to the collaboration and the exchange of experiences between the institutions involved in the project, with the aim to improve, fix and build new developments for the continuous improvement of the platform.

In this sense, collaborative conditions and environments will be facilitated when moving forward improvements that point to a common benefit of the entire platform, enabling inter-agency coordination mechanisms when necessary.
