= Orden del día

La función de agenda permite a un administrador definir el horario de una reunión. It's possible to define agenda items and
sub-items, with every one of the topics that will be discussed in the meeting, along with a description and the duration
of every item and sub-item.

imagen:componentes/meetings/TACa/TACa_frontend.png[Agenda en el frontend]

== Nuevo formulario de agenda

Para definir una agenda para una reunión:

. Iniciar sesión como administrador
. Ir al panel de administración
. En la barra lateral principal, haga clic en el botón para el espacio para el que desea configurar el componente.
Por ejemplo, podría ser "Procesos", "Colmenas" o "Conferencias"
. Haga clic en "Reuniones"
. Buscar en la reunión a la que desea agregar la agenda
. Haga clic en el botón "Agenda" imagen:action_monea.png[Agenda button]
. Rellene el formulario

imagen:componentes/meetings/TACa/new_schedula_form.png[Nuevo formulario de agenda en el backend]


.Nuevo formulario de agenda
|===
|Campo |Tipo |Descripción

|Título
|Requerido
|Título del orden del día. Por ejemplo, "Programa"

|Visible
|Opcional
|Marque si desea publicar la agenda.

|Elementos de la agenda
|Requerido
|Lista de elementos de la agenda.
|===

Es posible crear cualquier número de elementos de la Agenda y subítems. Puede subir o bajar la jerarquía de los puntos de la agenda.
También es posible eliminar y editar los elementos de la agenda.


.Formulario de elemento de agenda
|===
|Campo |Tipo |Descripción

|Título
|Requerido
|Título del punto del orden del día

|Duración
|Requerido
|Cuántos minutos durará el punto del orden del día. Por ejemplo, "15".

|Descripción
|Opcional
|Título del punto del orden del día

|Sub-elementos de la agenda
|Opcional
|Lista de subelementos de la agenda.
|===

La única limitación que tienen los puntos de la agenda y los subelementos es que tienen que respetar la duración del padre. Por ejemplo,
si hay un objeto que dura 60 minutos, no puedes crear un subelemento que dure 90 minutos.

Como ejemplo, este calendario:

imagen:componentes/meetings/TACa/TACa_frontend.png[Agenda en el frontend]

Tiene la siguiente configuración:

* Título: "Programa"
* Visible: verdadero
* Punto de la agenda #1:
** Título: Diagnóstico
** Duración: 60
* Punto de la agenda #2:
** Título: Ideación
** Duración: 120
** Sub-punto de la agenda #2.1:
*** Título: Pensamiento futuro
*** Duración: 60
*** Descripción: Imaginando cómo podemos resolver el problema
** Sub-punto de la agenda #2.2:
*** Título: Creando propuestas
*** Duración: 60
*** Descripción: En la plataforma