= Informationsseiten

partielle$legacy.adoc[]

Hier bieten wir Ihnen drei informative Seiten an, die Sie als Vorlage verwenden können oder den gelb markierten Text durch den korrekten Text ersetzen können. Die gleichen Dokumente finden Sie auf Spanisch oder Katalan in ihrem jeweiligen Decidim-Dokument.

== Informationen/FAQs

[[t.6a4146f0a2c8ecae39afa2642bcb7f700ef842af]][[t.0]]

[width="100%", cols="100%"]
|===
|_FAQS (EN)_

a|Wenn Sie an partizipatorischen Prozessen teilnehmen wollen und Ihr Sprichwort haben möchten, registrieren Sie sich! Beachten Sie, dass Sie, um einige der Funktionen bestimmter Prozesse (wie Stimmverhalten und Prioritäten) nutzen zu können, überprüfen müssen, dass Sie mit #Name der Gemeinde / Organisation#, registriert sind indem Sie einem sehr einfachen Schritt folgen.

*Was ist #Name der Gemeinde/ Organisation?#*

Eine Plattform für den Aufbau einer partizipatorischen #Name der Gemeinde/ Organisation#, mit einer gemeinsamen Vision und für die Vertiefung der lokalen partizipatorischen Demokratie.

#Platformname# ist eine partizipatorische Plattform basierend auf Open Code. Die Bürger können sehen, wie sie gebaut wird, und sie können sie wiederverwenden oder verbessern. https://www.google.com/url?q=https://github.com/AjuntamentdeBarcelona/decidim.barcelona&sa=D&ust=1526042251888000[Siehe den Code hier auf GitHub].

*Wie kann ich an der Plattform teilnehmen?*

Erhalten Sie Informationen

* Konsultieren Sie die aktiven Beteiligungsprozesse.
* Durchsuchen Sie die Vorschläge anderer Bürger
* Greifen Sie auf die Daten und Dokumente von persönlichen Treffen und die dort abgehaltenen Diskussionen und Debatten zu.
* Suchen Sie Inhalte, die für Sie von Interesse sind, nach Distrikt, Sachgebiet und Tags.

Nehmen Sie teil

* Machen Sie neue Vorschläge.
* Bieten Sie Argumente für oder dagegen, oder Ihre allgemeinen Gedanken.
* Teilen Sie die Vorschläge zu sozialen Medien.

a|Den bestehenden Vorschlägen folgen

* Befolgen Sie die bestehenden Vorschläge: diejenigen, die auf der Plattform begonnen wurden und die, die von persönlichen Treffen erzeugt wurden.
* Nach den persönlichen Treffen können Sie den Verlauf der Diskussionen und Debatten sowie die erzielten Beiträge verfolgen.
* Wählen Sie einen Vorschlag von Interesse für Sie und verfolgen Sie seine gesamten Fortschritte, von den Kommentaren anderer bis hin zu den endgültigen Dokumenten.

*Was gibt...?*

*Teilnehmende Prozes*

*#Plattformname#* Aktivitäten, die Bürger betreffen und die in mehreren Phasen durchgeführt werden: Information, Diagnose, Beiträge, Entscheidungen, Ergebnisse und Bewertung der Vorschläge.

*Schwärmere*

Permanente partizipatorische Kanäle und Körper.

*Begegnungen von Angesicht zu Angesicht:*

Treffen und Arbeitssitzungen zur Mitwirkung an aktiven Beteiligungsprozessen.

*Umfrage*

Fragebogen für die Bereitstellung von Informationen und den Austausch Ihrer Meinung.

*Diskussionen und Debatten*

Digitale Räume, um sich über die Vorschläge in den Prozessen zu informieren und zu entscheiden, die diese Funktion aktiviert haben.

*Vorschläge*

Beiträge, die Sie als Benutzer machen können. In einigen Fällen können Sie Stimmen von anderen Benutzern erhalten. Einige von ihnen werden eine Entscheidungsfunktion haben, andere eine rein beratende Funktion. Jeder Prozess wird seine eigenen charakteristischen Regeln haben.

*Kommentar*

Beiträge, die Sie als Benutzer als Antwort auf einen Vorschlag oder Diskussion und Debatte leisten können.

*Meine Wohnsitzüberprüfung funktioniert nicht.*

Überprüfen Sie die folgenden Möglichkeiten:

* Haben Sie Ihre nationale ID-Nummer oder Ihr Dokument ohne Leerzeichen zwischen den Ziffern, einschließlich des Endbuchstabens, eingegeben?
* Sind Sie sicher, dass Sie ein registrierter Einwohner in der Gemeinde #Name der Gemeinde/ Organisation#? (Die Gemeinde ist geographisch kleiner als die Metropolregion von Barcelona und die Provinz Barcelonas.)
* Es kann ein Problem mit Ihren Daten im Wohnsitzregister geben. Überprüfen Sie Ihre nächste CITIZEN HILFE UND INFORMATIONEN OFFICE und bestätigen Sie, dass Ihre Registrierungsinformationen korrekt sind.

Wenn alle oben genannten Schritte das Problem nicht lösen, senden Sie uns eine E-Mail an #Email# oder kommen Sie zu den persönlichen Diskussionen und Debatten für jeden Prozess.

*Ich bin kein registrierter Einwohner in #Name der Gemeinde / Organisation#; Warum kann ich nicht für die Vorschläge stimmen?*

Nur registrierte Einwohner in #Name der Gemeinde / Organisation# dürfen in Prozessen abstimmen, über die Vorschläge abgestimmt werden können. Wenn es um Fragen geht, die speziell für die Stadt zu treffende Entscheidungen betreffen Es sind die Bewohner der Stadt, die an solchen Entscheidungen mitwirken müssen.

Es ist wahr, dass es Personen gibt, die nicht registriert sind #Name der Gemeinde/ Organisation# Einwohner, die noch von diesen Entscheidungen betroffen sein können. aber das Register ist die breiteste verfügbare Volkszählung, die wir in #Name der Gemeinde / Organisation#: es ermöglicht uns, die maximale Anzahl von Personen zu erreichen und gleichzeitig zu garantieren, dass der partizipative Prozess sicher ist. Auf der anderen Seite, nicht alle Prozesse, die von der Plattform gestartet werden, erfordern ihre Teilnehmer registrierte Einwohner in der Stadt.

*Ich bin nicht registriert #Name der Gemeinde/ Organisation# Einwohner. Kann ich teilnehmen?*

Ja, Sie können daran teilnehmen, auch wenn Sie kein registrierter Wohnsitz sind. Sie können an mehreren aktivierten Prozessen, an persönlichen Diskussionen und Debatten teilnehmen und Sie können einen Vorschlag machen, ohne dass Sie ein registrierter Wohnsitz sein müssen. Nur in einigen Fällen beschränkt sich die Zustimmung zu Vorschlägen auf registrierte Einwohner, so wie nur registrierte Einwohner bei Kommunalwahlen wählen können.

*Warum muss ich mein Konto bestätigen?*

Sie benötigen ein Benutzerkonto, um die Plattform zu nutzen. Je nach Grad der Überprüfung können Sie mehr oder weniger Dinge tun:

* Wenn Sie sich auf der Website über eine E-Mail-Adresse anmelden, ohne weitere Informationen anzugeben (so dass der Überprüfungsprozess nicht durchgeführt wird), Sie werden in der Lage sein, Vorschläge zu kommentieren und zu diskutieren.
* Wenn Sie nach der Registrierung die grundlegende Verifizierung durchgeführt haben, d.h. Sie haben Ihren Wohnsitz über die Plattform überprüft (mehr Informationen unter "Wie erstelle und verifiziere ich mein Konto? ), können Sie für Vorschläge in Prozessen stimmen, die durchführbar sind (in bestimmten Prozessen).
* Sie können jederzeit persönlich teilnehmen und an jedem persönlichen Treffen für jeden Teilnahmeprozess teilnehmen. Beiträge, die von Angesicht zu Angesicht gemacht werden, werden gesammelt, veröffentlicht und zugänglich für die Plattform.

*Benötige ich ein Mobiltelefon oder Internetzugang, um teilzunehmen?*

Nein. Sie können alle Maßnahmen im Zusammenhang mit den Vorschlägen durchführen - sei es für die Erstellung, die Unterstützung, dafür zu stimmen oder darüber informiert zu werden - Angesicht zu Angesicht bei allen Diskussionen und Debatten, die geführt werden. Sie können auch ein vollständig verifiziertes Benutzerkonto erstellen, wenn Sie die Plattform nutzen möchten.

*Wie erstelle und bestätige ich mein Konto?*

Der erste Schritt ist die Erstellung eines Kontos. Erstellen Sie das Konto und geben Sie die gewünschten Informationen ein. Sie müssen das Kästchen anklicken und angeben, dass Sie unsere Nutzungsbedingungen akzeptieren. Beim Erstellen eines neuen Kontos wird eine E-Mail an die angegebene Adresse gesendet, und Sie müssen auf den Link klicken, den es enthält (der Link "Mein Konto bestätigen") um die Erstellung des Kontos abzuschließen.

Sobald Ihr Basiskonto erstellt wurde und Sie sich mit Ihrer E-Mail und Ihrem Passwort angemeldet haben, das System gibt Ihnen die Möglichkeit, eine grundlegende Überprüfung durchzuführen. Um dies zu tun, klicken Sie auf den Link "Mein Konto" oben rechts und klicken Sie dann auf "Mein Konto verifizieren".

Einige Prozesse, wenn nötig, erfordern auch, dass Sie Ihre Wohnsitzdaten eingeben um zu überprüfen, dass du ein registrierter Bewohner in #Name der Gemeinde / Organisation ist# (es ist wichtig, die Dokumentnummer zusammen mit dem Buchstaben und Ihrem Geburtsdatum einzugeben, und markieren Sie das Kästchen, in dem Sie den Zugang zum Stadtregister akzeptieren). Wenn Ihre Daten korrekt sind, können Sie mit Ihrem Konto die Vorschläge unterstützen.

*Ich habe mein Passwort vergessen und mein Konto funktioniert nicht. Was kann ich tun? *

Sie können ein neues Passwort anfordern, das an Ihre E-Mail-Adresse gesendet wird. Wenn die obige Lösung nicht funktioniert, können Sie uns eine E-Mail an #Email#, und wir werden das Problem lösen, das mit Ihrem Konto verbunden ist. Prozesse, die persönliche Meetings beinhalten, stehen Ihnen zur Teilnahme und Teilnahme offen, ohne dass Sie sich auf der Plattform registrieren müssen.

*Wie kann ich meine E-Mail-Adresse, meinen Benutzernamen, mein Passwort, das Abmelden oder Aktivieren von Benachrichtigungen ändern, die an die E-Mail-Adresse gesendet werden?*

Klicken Sie auf den Link "Enter", geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein und klicken Sie auf "Enter". Sobald Sie dies getan haben, klicken Sie auf den Link "Mein Konto", wo Sie alle Optionen finden werden, Sie können Ihre E-Mail-Adresse oder Ihren Benutzernamen ändern, sich abmelden oder Benachrichtigungen aktivieren/deaktivieren. Sobald Sie die entsprechenden Änderungen vorgenommen haben, stellen Sie sicher, dass Sie auf die Schaltfläche "Änderungen speichern" klicken.

*Ich kann mein Konto nicht korrekt erstellen.*

Überprüfen Sie den Abschnitt "Überprüfung meines Wohnsitzes funktioniert nicht", falls das Problem in diesem Schritt liegt; im Allgemeinen ist dies das häufigste Problem. Wenn dies Ihr Problem nicht löst, überprüfen Sie den Abschnitt "Wie Sie mein Konto erstellen und überprüfen", um sicherzustellen, dass Sie die Schritte korrekt befolgen. Wenn das Problem weiterhin besteht, senden Sie uns eine E-Mail an #Email#, und Sie erhalten Hilfe.
|===

[[h.mkf6otb3mhlh]]
== Nutzungsbedingungen

[[t.0c2d2bc083254e4010a82a1ac81ebd7f18f135ee]][[t.1]]

[width="100%", cols="100%"]
|===
|_Nutzungsbedingungen (EN)_

a|Rechtliche Aspekte und Nutzungsbedingungen für die #Platformname# partizipative Plattform unter #Name der Gemeinde / Organisation# Stadtrat.

(die von den juristischen Diensten empfohlenen Empfehlungen. Du kannst die https://www.google.com/url?q=https://decidim.barcelona/pages/terms-and-conditions&sa=D&ust=1526042251902000[Decidim.Barcelona Nutzungsbedingungen] als Modell verwenden).
|===

[[h.3oy7u29]]
== Wie die Plattform funktioniert

[[t.44b67a895959076674b8c3aa044e22bbd448f440]][[t.2]]

[width="100%", cols="100%"]
|===
|_Barrierefreiheit (EN)_

a|Dies bezieht sich auf das Design und den Inhalt der Webseite, die zugänglich sein müssen (ohne irgendwelche visuellen oder technologischen Hindernisse und für die größtmögliche Anzahl von Nutzern), und den Standardregeln (WAI, Web Accessibility Initiative).

Decidim.Barcelona Beispiel https://www.google.com/url?q=https://www.decidim.barcelona/pages/accessibility&sa=D&ust=1526042251903000[Accessibility].
|===