= Páginas de información

include::parcial$legacy.adoc[]

Aquí le ofrecemos tres páginas informativas que puede utilizar como plantilla o reutilizar reemplazando el texto resaltado en amarillo por el texto correcto. Puede encontrar los mismos documentos en español o catalán en su respectivo documento Decidim de Administro.

== Información/FAQs

[[t.6a4146f0a2c8ecae39afa2642bcb7f700ef842af]][[t.0]]

[width="100%", cols="100%"]
|===
|_Preguntas frecuentes)_

a|Si desea participar en procesos participativos y tener su opinión, ¡inscríbete! Tenga en cuenta que para utilizar algunas de las funciones de ciertos procesos (como votar y priorizarse) tendrá que verificar que está registrado con #Nombre de la organización Municipalidad#, siguiendo un paso muy sencillo.

*¿Qué es #Nombre de la Municipalidad/ Organización?#*

Plataforma para construir un #Nombre más participativo del Municipio / Organización#, con una visión compartida y para profundizar en la democracia participativa local.

#Platformname# es una plataforma participativa basada en código abierto. Los ciudadanos pueden ver cómo se construye y pueden reutilizarla o mejorarla. https://www.google.com/url?q=https://github.com/AjuntamentdeBarcelona/decidim.barcelona&sa=D&ust=1526042251888000[Revisa el código aquí en GitHub].

*¿Cómo puedo participar en Plataforma?*

Informar

* Consulte los procesos participativos activos.
* Navegar por las propuestas realizadas por otros ciudadanos
* Acceda a los datos y documentos de las reuniones cara a cara, así como a las discusiones y debates celebrados allí.
* Busque contenido de interés para usted, por distrito, asunto y etiquetas.

Participar

* Haga nuevas propuestas.
* Ofrecer argumentos a favor o en contra, o sus ideas generales.
* Comparta las propuestas sobre los medios de comunicación social.

a|Siga las propuestas existentes

* Siga las propuestas existentes: las iniciadas en la plataforma y las generadas por reuniones cara a cara.
* Después de que se hayan celebrado las reuniones cara a cara, puede seguir el progreso de las discusiones y los debates, así como las contribuciones generadas.
* Elija una propuesta de interés para usted y siga todo su progreso, desde los comentarios realizados por otros hasta los documentos finales.

*¿Qué son...?*

*Procesos participativos*

*#Nombre de la plataforma#* actividades que implican a los ciudadanos y que se llevan a cabo en varias etapas: información, diagnóstico, contribuciones, decisiones, resultados y evaluación de las propuestas.

*Colmenas*

Canales y cuerpos participativos permanentes.

*Reuniones cara a cara:*

Reuniones y sesiones de trabajo para contribuir a los procesos participativos activos.

*Encuestas*

Cuestionario para proporcionar información y compartir su opinión.

*Debates y debates*

Espacios digitales para informarse y decidir sobre las propuestas en los procesos que tienen esta función habilitada.

*Propuestas*

Contribuciones que puedes hacer como usuario. En algunos casos podrás recibir votos de otros usuarios. Algunos de ellos tendrán una función de toma de decisiones y otros una función meramente consultiva. Cada proceso tendrá sus propias reglas características.

*Comentarios*

Contribuciones que usted puede hacer como usuario en respuesta a una propuesta o discusión y debate.

*La verificación de mi residencia no funciona.*

Compruebe las siguientes posibilidades:

* ¿Ha introducido su número nacional de identificación o documento sin espacios entre los dígitos, incluyendo la carta final?
* ¿Estás seguro de que eres un residente registrado en el municipio de #Name of the Municipality/ Organization#? (El municipio es geográficamente más pequeño que el Área Metropolitana de Barcelona y el Provenza de Barcelona)
* Puede haber un problema con sus datos en el registro de residencia. Consulte su OFICINA DE CITIZEN HELP E INFORMACIÓN más cercana y confirme que su información de registro es correcta.

Si todos los pasos anteriores no resuelven el problema, envíenos un correo electrónico a #Email# o venga a las discusiones y debates cara a cara para cada proceso.

*No soy un residente registrado en #Nombre del Municipio / Organización#; ¿por qué no puedo votar a favor de las propuestas?*

Sólo los residentes registrados en #Nombre de la Municipalidad/Organización# pueden votar en procesos en los que se pueden votar las propuestas. Cuando se trata de cuestiones que afectan a las decisiones a tomar que son específicas de la ciudad, son los residentes de la ciudad los que necesitan participar en este tipo de toma de decisiones.

Es cierto que hay personas que no están inscritas en #Nombre de la Municipalidad/Organización# que todavía pueden verse afectadas por estas decisiones. pero el Registro es la cuna más amplia disponible que tenemos en #Name of the Municipality/ Organization#: nos permite alcanzar el máximo número de personas garantizando al mismo tiempo la seguridad del proceso participativo. Por otra parte, no todos los procesos iniciados desde la plataforma requieren que sus participantes estén registrados en la ciudad.

*No soy un #Nombre registrado de la Municipalidad/Organización# residente. ¿Puedo participar?*

Sí, puede participar incluso cuando no es un residente inscrito. Puede tomar parte en varios procesos habilitados, en discusiones y debates cara a cara, y usted puede lanzar una propuesta, sin tener que ser un residente inscrito. Sólo en algunos procesos la votación de propuestas se limita a los residentes registrados, del mismo modo que sólo los residentes registrados pueden votar en las elecciones municipales.

*¿Por qué tengo que verificar mi cuenta?*

Necesitas una cuenta de usuario para usar la plataforma. Puedes hacer más o menos cosas dependiendo del grado de verificación:

* Si se registra en el sitio web a través de una dirección de correo electrónico sin proporcionar ninguna información adicional (por lo que el proceso de verificación no se lleva a cabo), podrán comentar y debatir propuestas.
* Si después de registrarse, ha realizado la verificación básica, p.e. has verificado tu residencia a través de la plataforma (más información en "¿Cómo puedo crear y verificar mi cuenta? ), puede votar por propuestas en procesos que son feasibles (en ciertos procesos).
* Usted siempre puede participar en persona y en cualquiera de las reuniones cara a cara hay para cada proceso participativo. Las contribuciones que se hagan cara a cara serán recogidas, publicadas y accesibles a la plataforma.

*¿Necesito un teléfono móvil o acceso a Internet para participar?*

No. Puede llevar a cabo cualquier acción relacionada con las propuestas - ya sea para crear, apoyar, votar a favor o informarse sobre ellos - cara a cara en cualquiera de las discusiones y debates que se celebran. También puede crear una cuenta de usuario completamente verificada si desea utilizar la plataforma.

*¿Cómo puedo crear y verificar mi cuenta?*

El primer paso es crear una cuenta. Cree la cuenta y rellene la información que se le solicita. Usted debe marcar la casilla indicando que acepta nuestros términos y condiciones de usuario. Al crear una nueva cuenta, se enviará un correo electrónico a la dirección especificada, y tendrás que hacer clic en el enlace que contiene (el enlace "Confirmar mi cuenta" ) para completar la creación de la cuenta.

Una vez que tu cuenta básica ha sido creada y has iniciado sesión usando tu correo electrónico y contraseña, el sistema le dará la opción de realizar una verificación básica. Para ello, haga clic en el enlace "Mi cuenta" en la parte superior derecha y luego haga clic en el botón "Verificar mi cuenta".

Algunos procesos, si es necesario, también requerirán que introduzca sus datos de residencia, para verificar que usted es un residente registrado en #Nombre de la Municipalidad/Organización# (es importante introducir el número del documento junto con la carta y la fecha de nacimiento, y marque la casilla indicando que acepta el acceso al Registro Municipal). Si sus datos son correctos, su cuenta le permitirá apoyar las propuestas.

*He olvidado mi contraseña y mi cuenta no funciona. ¿Qué puedo hacer?*

Puede solicitar una nueva contraseña, que se enviará a su dirección de correo electrónico. Si la solución anterior no funciona, puede enviarnos un correo electrónico a #Email#, y resolveremos el problema asociado con su cuenta. Los procesos que incluyen reuniones cara a cara están a su disposición para asistir y participar, sin necesidad de registrarse en la plataforma.

*¿Cómo puedo cambiar mi dirección de correo electrónico, mi nombre de usuario, mi contraseña, cancelar la suscripción o desactivar las notificaciones que se envían a la dirección de correo electrónico?*

Haga clic en el enlace "Intro", introduzca su dirección de correo electrónico y contraseña y haga clic en el botón "Intro". Una vez que lo haya hecho, haga clic en el enlace "Mi cuenta", donde encontrará todas las opciones, permitiéndole cambiar su dirección de correo electrónico o nombre de usuario, cancelar la suscripción o activar o desactivar notificaciones. Una vez que haya realizado los cambios apropiados, asegúrese de hacer clic en el botón "Guardar cambios".

*No puedo crear mi cuenta correctamente.*

Revise la sección "Mi verificación de residencia no funciona", en caso de que el problema esté en este paso; en general, este es el problema más frecuente. Si esto no resuelve tu problema, revisa la sección "Cómo crear y verificar mi cuenta", para asegurarse de que está siguiendo los pasos correctamente. Si el problema persiste, envíanos un correo electrónico a #Email#, y recibirás ayuda.
|===

[[h.mkf6otb3mhlh]]
== Términos y condiciones de uso

[[t.0c2d2bc083254e4010a82a1ac81ebd7f18f135ee]][[t.1]]

[width="100%", cols="100%"]
|===
|_Términos y condiciones de uso)_

a|Aspectos legales y condiciones de uso para la plataforma participativa #Platformname# en #Name of the Municipality/ Organization# Ayuntamiento.

(los que los servicios legales le recomiendan). Puede utilizar https://www.google.com/url?q=https://decidim.barcelona/pages/terms-and-conditions&sa=D&ust=1526042251902000[Decidim.Barcelona términos y condiciones de uso] como modelo).
|===

[[h.3oy7u29]]
== Cómo funciona la plataforma

[[t.44b67a895959076674b8c3aa044e22bbd448f440]][[t.2]]

[width="100%", cols="100%"]
|===
|_Accesibilidad → _

a|Esto se refiere al diseño y contenido de la página web, que deben ser accesibles (sin obstáculos visuales o tecnológicos y para el mayor número posible de usuarios), y a las regulaciones estándar (WAI, Web Accessibility Initiative o Iniciativa de Accesibilidad Web).

Ejemplo de Decidim.Barcelona https://www.google.com/url?q=https://www.decidim.barcelona/pages/accessibility&sa=D&ust=1526042251903000[Accessibility].
|===