= Temporäre Verifizierungen

== Die Grundlagen verstehen

In Decidim gibt es hauptsächlich zwei Arten von Teilnehmenden:

- Einmalige Teilnehmende: Nutzende, die die Plattform für eine einzelne Aktion nutzen, wie z. B. das Abstimmen bei partizipativen Budgets, und danach nicht wiederkehren.
- Wiederkehrende Teilnehmende: Nutzende, die sich regelmässig an verschiedenen Beteiligungsprozessen beteiligen.

Für einmalige Teilnehmende können die Registrierung und der Verifizierungsprozess eine Hürde darstellen, die zu unvollständiger Teilnahme führt. Um dem entgegenzuwirken, führt Decidim die temporäre Verifizierungsmethode ein, mit der Nutzende ihre Identität verifizieren und teilnehmen können, ohne ein Konto zu registrieren.

Die temporäre Verifizierungsmethode wurde entwickelt, um die Teilnahme für einmalige Nutzende zu vereinfachen, indem eine direkte Verifizierung ohne Kontoerstellung ermöglicht wird.

NOTE: Diese Funktion ist für eine begrenzte Dauer während eines bestimmten Beteiligungsprozesses gedacht, z. B. während einer Abstimmungsphase eines partizipativen Budgets.

=== Wie funktioniert es?

Diese Funktion ermöglicht es Teilnehmenden, ohne Registrierung auf der Plattform teilzunehmen, indem sie ihre Identität mit dem von der Organisation gewählten System verifizieren. Die wichtigsten Merkmale sind:

- **Direkte Verifizierung ohne Registrierung:** Teilnehmende können sich verifizieren und ihre Aktion abschliessen, ohne sich anzumelden.
- **Auf Komponentenebene konfigurierbar:** Admins können die temporäre Verifizierung für bestimmte Komponenten aktivieren oder deaktivieren, wie bei allen Verifizierungsmethoden.
- **Temporäre Sitzung**: Wenn Teilnehmende verifiziert werden, wird eine temporäre Sitzung eröffnet. Diese Sitzung erlaubt es Teilnehmenden nur, Aktionen in der jeweiligen Komponente abzuschliessen. Wenn die temporär verifizierte Person die Komponente verlassen möchte, wird die Sitzung geschlossen.
- **Fokusmodus:** Beim Ausführen der eingeschränkten Aktion über die temporäre Verifizierung wird ein Fokusmodus aktiviert, damit die Aufmerksamkeit der teilnehmenden Person auf die Hauptaktion gerichtet bleibt.
- **Verknüpfung mit einer bestehenden Verifizierungsmethode:** Die temporäre Verifizierung muss mit einer bereits bestehenden Verifizierungsmethode verknüpft werden (zum Beispiel einer Zählung der Organisation).
- **Widerruf früherer Verifizierungen:** Beim Aktivieren der temporären Verifizierung werden alle vorherigen Verifizierungen widerrufen, um Verifizierungskonflikte zu vermeiden.
- **Abrufen der temporären Sitzung**. So können temporär verifizierte Teilnehmende sich erneut verifizieren und sich mit der temporären Sitzung anmelden. So können sie ihre Stimmen einsehen und ändern.

== Konfiguration

Um die temporäre Verifizierung zu aktivieren, gehen Sie wie folgt vor:

1. Auf das Systempanel zugreifen.
1. Die Methode der temporären Verifizierung aktivieren.
1. Sie mit einer bestehenden Verifizierungsmethode verknüpfen (zum Beispiel einer Zählung der Organisation).
1. Zum Admin-Dashboard gehen.
1. Die Berechtigungen für die temporäre Verifizierung in einer Komponente aktivieren.
1. Die Aktion bestätigen, wodurch alle aktuellen Verifizierungen widerrufen werden.
1. Grossartig! Sie haben die temporäre Verifizierung für eine bestimmte Komponente aktiviert.

== Beispiele

Um besser zu verstehen, wie diese Funktion funktioniert, erklären wir im Folgenden die verschiedenen Abläufe und Sonderfälle:

=== Ablauf 1: Nicht registrierte besuchende Person

1. Als nicht registrierte besuchende Person klicke ich auf die eingeschränkte Aktion
1. Daraufhin wird mir das Verifizierungsformular angezeigt, das ich mit meinen Daten ausfülle
1. So werde ich erfolgreich verifiziert
1. Anschliessend wird eine temporäre Sitzung eröffnet
1. Und ich erhalte Zugang zur eingeschränkten Aktion
1. Wenn ich die Aufgabe abgeschlossen habe (z. B. Abstimmung bei einem partizipativen Budget). Dann kann ich den Fokusmodus verlassen und die temporäre Sitzung wird geschlossen.

=== Ablauf 2: Registrierte teilnehmende Person mit angemeldeter Sitzung

1. Als angemeldete registrierte teilnehmende Person klicke ich auf die eingeschränkte Aktion
1. Daraufhin wird mir das Verifizierungsformular angezeigt, das ich mit meinen Daten ausfülle
1. So werde ich erfolgreich verifiziert
1. Dann erhalte ich Zugang zur eingeschränkten Aktion
1. Anschliessend wird die Verifizierung in meinem Profil gespeichert

=== Sonderfälle

==== Ablauf 3: Verifizierungskonflikte vermeiden

1. Als besuchende Person versuche ich, mich mit den Daten einer bereits verifizierten registrierten teilnehmenden Person zu verifizieren.
1. Das System erkennt einen Verifizierungskonflikt.
1. Daraufhin werde ich daran gehindert, die Verifizierung fortzusetzen.

==== Ablauf 4: Zusammenführen von temporären und registrierten Konten

1. Als temporär verifizierte Person, die den Abstimmungsprozess abgeschlossen hat. Und ihre temporäre Sitzung geschlossen hat.
1. Auf der Plattform registrieren.
1. Versuchen, sich mit denselben persönlichen Daten zu verifizieren.
1. Das System ruft Ihre temporären Nutzendendaten ab und führt sie mit Ihrem neuen registrierten Konto zusammen.
1. Sie können nun Ihre Stimmen einsehen und bearbeiten.

=== Wie funktioniert die temporäre Sitzung?

1. Diese Sitzung erlaubt es Ihnen nur, Aktionen in der jeweiligen Komponente auszuführen. Wenn die temporär verifizierte Person die Komponente verlassen möchte, wird die Sitzung geschlossen.
1. Die Sitzung wird nach einer gewissen Zeit der Inaktivität geschlossen.
1. Die Sitzung kann wiederhergestellt werden. Das bedeutet, dass wenn Sie erneut versuchen, sich mit denselben Daten zu verifizieren, Ihre Sitzung wiederhergestellt wird und Sie Ihre Stimmen einsehen und bearbeiten können.