[bibliography]
= {academic-label}
:page-partial:
include::decidim::partial$l10n.adoc[]

[[refs]]
[[ref-4881969-DJZCCH7V]]
* Barandiaran, X. E. (2019). Tecnopolítica, municipalismo y radicalización democrática. In L. Roth, A. Monterde, & A. Calleja-López (Eds.), _Ciudades Democráticas. La revuelta municipalista en el ciclo post-15M_ (pp. 173–207). Icaria. http://ciudadesdemocraticas.tecnopolitica.net/

[[ref-4881969-INGW3H3C]]
* Solà, J. (2018). _How are decisions made in Decidim.barcelona_ [Master Thesis, Pompeu Fabra]. https://repositori.upf.edu/handle/10230/36105

[[ref-4881969-ZEYELQ5C]]
* Barandiaran, X. E., Monterde, A., & Pin, G. (2016a). Decidim.barcelona: autonomia, participació i programari lliure. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32).

[[ref-4881969-XCEET6WF]]
* Barandiaran, X. E., Monterde, A., & Pin, G. (2016b). Decidim.barcelona: autonomía, participación y software libre - Software libre. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32). http://softwarelibre.xarxaip.cat/18.html

[[ref-4881969-LII99ZM9]]
* Aragón, P., Kaltenbrunner, A., Calleja-López, A., Pereira, A., Monterde, A., Barandiaran, X. E., & Gómez, V. (2017). Deliberative Platform Design: The Case Study of the Online Discussions in Decidim Barcelona. _Social Informatics_, 277–287. https://doi.org/10.1007/978-3-319-67256-4_22 +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# With the irruption of ICTs and the crisis of political representation, many online platforms have been developed with the aim of improving participatory democratic processes. However, regarding platforms for online petitioning, previous research has not found examples of how to effectively introduce discussions, a crucial feature to promote deliberation. In this study we focus on the case of Decidim Barcelona, the online participatory-democracy platform launched by the City Council of Barcelona in which proposals can be discussed with an interface that combines threaded discussions and comment alignment with the proposal. This innovative approach allows to examine whether neutral, positive or negative comments are more likely to generate discussion cascades. The results reveal that, with this interface, comments marked as negatively aligned with the proposal were more likely to engage users in online discussions and, therefore, helped to promote deliberative decision making.pass:[</div>]

[[ref-4881969-SCKIHAIX]]
* Barandiaran, X. E., Calleja-López, A., & Monterde, A. (n.d.). _Decidim: political and technopolitical networks for participatory democracy. White Paper_. Retrieved March 16, 2019, from https://docs.decidim.org/whitepaper/en/doc-info/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# Decidim [http://decidim.org], from the Catalan for “let’s decide” or “we decide”, is a digital infrastructure for participatory democracy, built entirely and collaboratively as free software. More specifically, Decidim is a web environment (a framework) produced in Ruby on Rails (a programming language) that allows anybody to create and configure a website platform, to be used in the form of a political network for democratic participation. The platform allows any organization (local city council, association, university, NGO, neighbourhood or cooperative) to create mass processes for strategic planning, participatory budgeting, collaborative design for regulations, urban spaces and election processes. It also makes possible to connect traditional in-person democratic meetings (assemblies, council meetings, etc.) with the digital world: sending meeting invites, managing registrations, streaming content, facilitating the publication of meeting minutes, etc. In addition, Decidim enables the structuring of government bodies or assemblies (councils, boards, working groups), the convening of consultations, referendums or channelling citizen or member initiatives to trigger different decision making processes. However, the Decidim project is much more than its technological features. Decidim is in itself a sort of crossroad of the various dimensions of networked democracy and society, a detailed practical map of their complexities and conflicts. We distinguish three general planes or dimensions of the project: the political (focused on the democratic model that Decidim promotes and its impact on public policies and organizations), the technopolitical (focused on how the platform is designed, the mechanisms it embodies, and the way in which it is democratically designed), and the technical (focused on the conditions of production, operation and success of the project: the factory, collaborative mechanisms, licenses, etc.).pass:[</div>]

[[ref-4881969-YCAWSJCB]]
* Borge, R., Balcells, J., Padró-Solanet, A., Batlle, A., Orte, A., & Serra, R. (n.d.). _La participación política a través de la plataforma Decidim: análisis de 11 municipios catalanes_.
