= English Publications

== Media

* Barandiaran, X. E., & iaran. (2018, April 24). _What is Decidim?_ https://xabier.barandiaran.net/2018/04/24/what-is-decidim/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# Many people ask what is this project called “Decidim” to which I have devoted my last two year of work with complete dedication. I wanted to share a brief summary here. This text is the…pass:[</div>]

* Stark, K. (2017, May 9). _Barcelona’s Decidim Offers Open-Source Platform for Participatory Democracy Projects_. https://www.shareable.net/blog/barcelonas-decidim-offers-open-source-platform-for-participatory-democracy-projects +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# The word Decidim translated from Catalan means we decide, and it’s the name of Barcelona’s digital infrastructure for participatory democracy. One part functional database and one part political statement, organizers say Decidim is key to a broad digital transformation that is taking place in Barcelona — its institutions, markets, and economy.pass:[</div>]

* _Decidim: Free Open-Source participatory democracy for cities and organizations | Hacker News_. (n.d.). Retrieved January 21, 2019, from https://news.ycombinator.com/item?id=18952328

* Oikos Denktank. (n.d.). _(W)E-Democracy - speaker 5 (1) - E-democratic cities - Arnau Monterde and Xabier E. Barandiaran_. Retrieved August 30, 2017, from https://www.youtube.com/watch?v=qrQ8ij4Ekag
