[.publications]
= English Publications

== Media

* Barandiaran, X. E. (2018, April 24). _What is Decidim?_ https://xabier.barandiaran.net/2018/04/24/what-is-decidim/
+
.Abstract
[%collapsible]
====
Many people ask what is this project called “Decidim” to which I have devoted my last two year of work with complete dedication. I wanted to share a brief summary here. This text is the introduction of the Decidim’s White Paper (I am writing with Antonio Calleja and Arnau Monterde), to be published soon. I have systematized this text myself but it is really the product of a big group of people that have contributed to this project since its inception (Arnau Monerde, Andrés Lucena, Antonio Calleja, Carol Romero, Pablo Aragón and many others).
====

* Stark, K. (2017, May 9). _Barcelona’s Decidim Offers Open-Source Platform for Participatory Democracy Projects_. https://www.shareable.net/blog/barcelonas-decidim-offers-open-source-platform-for-participatory-democracy-projects
+
.Abstract
[%collapsible]
====
The word Decidim translated from Catalan means we decide, and it’s the name of Barcelona’s digital infrastructure for participatory democracy. One part functional database and one part political statement, organizers say Decidim is key to a broad digital transformation that is taking place in Barcelona — its institutions, markets, and economy.
====

* _Decidim: Free Open-Source participatory democracy for cities and organizations | Hacker News_. (n.d.). Retrieved January 21, 2019, from https://news.ycombinator.com/item?id=18952328

* Oikos Denktank. (n.d.). _(W)E-Democracy - speaker 5 (1) - E-democratic cities - Arnau Monterde and Xabier E. Barandiaran_. Retrieved August 30, 2017, from https://www.youtube.com/watch?v=qrQ8ij4Ekag
