
= French Publications

== Media

* Politics, O. S. (2018a, March 7). _Decidim, la plateforme de participation citoyenne d’envergure européenne_. https://opensourcepolitics.eu/actualites/decidim-la-plateforme-de-participation-citoyenne-denvergure-europeenne/
+
.Abstract
[%collapsible]
====
Cet article sur Decidim (plateforme de participation citoyenne) est basé sur une série de conversations que nous avons eues avec Pablo Aragon, Xabier Barandiaran, Josep Jaume et de nombreux autres collaborateurs du projet open source Decidim.
====

* Politics, O. S. (2018b, March 7). _Le Contrat Social de Decidim, un texte fondateur_. https://opensourcepolitics.eu/actualites/le-contrat-social-de-decidim-un-texte-fondateur/
+
.Abstract
[%collapsible]
====
Nous reproduisons ici, pour la première fois en français, le « Contrat Social » de la plateforme Decidim, traduit du catalan en passant par l’anglais. Toute traduction implique nécessairement des choix, qui peuvent par endroit altérer l’intention initiale de la phrase, mais nous avons tenté de restituer au mieux l’esprit de l’original.

Le choix d’intituler ce document « Contrat social » est lourd de sens puisque ce concept est l’un des plus connus de la philosophie politique. Initialement théorisé par Grotius au 17ème siècle avant d’être popularisé par Hobbes, Locke et Rousseau, le contrat social constitue une hypothèse de réponse à plusieurs questions philosophiques fondamentales. L’objectif est en effet de fournir un cadre conceptuel permettant d’expliquer la fondation de la société et de comprendre pourquoi l’être humain se soumet à des règles auxquelles il n’a pas choisi explicitement de se soumettre.

L’idée derrière la reprise de cette notion par les fondateurs de Decidim est donc d’assumer le développement d’un nouveau fonctionnement politique à travers l’adoption de cette plateforme. C’est donc la marque d’un renouvellement de la compréhension de notre participation, en tant qu’individus politiques, à la société. Cette conception renouvelée du poids politique du citoyen est issue directement, dans le cas de Decidim, de la relation étroite des leaders du projet avec le mouvement des Indignés, qui souhaitait explicitement refonder l’organisation du pouvoir politique pour obtenir une démocratie plus ouverte.
====
