[bibliography]
= {media-mentions-label}
:page-partial:
include::decidim::partial$l10n.adoc[]

[[refs]]
[[ref-4881969-ZKNJCZHV]]
* _Why we should dispel the negative image of smart cities_. (2019, September 12). https://www.information-age.com/negative-image-of-smart-cities-123485288/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# Mikael Sandberg, chairman of VXFIBER, explains why we should think more positively about the benefits smart citiespass:[</div>]

[[ref-4881969-GPZCWSHQ]]
* _Wie Barcelona eine offene “Smart City” im Dienste des Gemeinwohls plant_. (2018, September 9). https://netzpolitik.org/2018/freie-software-als-oeffentliches-gut-und-was-rathaeuser-dafuer-tun-koennen/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# Im Interview spricht Francesca Bria, Barcelonas Chief Technology and Digital Innovation Officer, über “Digitale Soziale Innovation” und passende Strategien um die lokale Wirtschaft, Privatsphäre und die demokratische Teilhabe der Bürger*innen auch in einer “Smart City” langfristig zu sichern und zupass:[</div>]

[[ref-4881969-FWFFK8LS]]
* _Perché Barcelona Smart City è un modello per il mondo. Intervista a Francesca Bria_. (2018, August 13). http://www.designatlarge.it/barcelona-smart-city-francesca-bria/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# La sovranità tecnologica ai cittadini. Ecco come Barcelona Smart City è diventata un modello per il mondo. Intervista alla CTO Francesca Briapass:[</div>]

[[ref-4881969-7R8A6K8U]]
* Bravo, E. (2016, July 20). _Cómo mejorar Barcelona con la participación de sus ciudadanos_ [Magazzine]. http://www.yorokobu.es/barcelona-participacion/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# El cricket es un deporte muy curioso. Los partidos pueden durar días y, entre sus reglas, está la de parar el juego para tomar el té. Una de las potencias en este deporte es Paquistán, país del que procede parte de la población inmigrante de Barcelona. Muchos de los miembros de esa comunidad llevan años […]pass:[</div>]

[[ref-4881969-B37NAD7Y]]
* Stark, K. (2017, May 9). _Barcelona’s Decidim Offers Open-Source Platform for Participatory Democracy Projects_. https://www.shareable.net/blog/barcelonas-decidim-offers-open-source-platform-for-participatory-democracy-projects +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# The word Decidim translated from Catalan means we decide, and it’s the name of Barcelona’s digital infrastructure for participatory democracy. One part functional database and one part political statement, organizers say Decidim is key to a broad digital transformation that is taking place in Barcelona — its institutions, markets, and economy.pass:[</div>]

[[ref-4881969-PYGT6HFK]]
* _TIPS - Cultura digital - La democracia 2.0_. (2017, February 2). http://www.rtve.es/alacarta/videos/tips/tips-cultura-digital-democracia-20/3896837/ +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# TIPS - Cultura digital - La democracia 2.0, Tips online, completo y gratis en RTVE.es A la Carta. Todos los programas de Tips online en RTVE.es A la Cartapass:[</div>]

[[ref-4881969-4AXAJHZX]]
* _Decidim: Free Open-Source participatory democracy for cities and organizations | Hacker News_. (n.d.). Retrieved January 21, 2019, from https://news.ycombinator.com/item?id=18952328

[[ref-4881969-3W22Z9CI]]
* Macher, J. (n.d.). _Digital und demokratisch (neues deutschland)_. Retrieved December 7, 2019, from https://www.neues-deutschland.de/artikel/1129769.smart-city-digital-und-demokratisch.html +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# In Barcelona bedeutet »Smart City«: Mehr Mitsprache für die Menschen. Andere Städte sind dem Beispiel gefolgt.pass:[</div>]
