= Spanish Publications

== Academic

* Barandiaran, X. E. (2019). Tecnopolítica, municipalismo y radicalización democrática. In L. Roth, A. Monterde, & A. Calleja-López (Eds.), _Ciudades Democráticas. La revuelta municipalista en el ciclo post-15M_ (pp. 173–207). Icaria. http://ciudadesdemocraticas.tecnopolitica.net/

* Solà, J. (2018). _How are decisions made in Decidim.barcelona_ [Master Thesis, Pompeu Fabra]. https://repositori.upf.edu/handle/10230/36105

* Barandiaran, X. E., Monterde, A., & Pin, G. (2016a). Decidim.barcelona: autonomia, participació i programari lliure. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32).

* Barandiaran, X. E., Monterde, A., & Pin, G. (2016b). Decidim.barcelona: autonomía, participación y software libre - Software libre. In Xarxaip (Ed.), _Programari lliure i de codi obert-Societat lliure i govern obert._ (pp. 31–32). http://softwarelibre.xarxaip.cat/18.html

* Aragón, P., Kaltenbrunner, A., Calleja-López, A., Pereira, A., Monterde, A., Barandiaran, X. E., & Gómez, V. (2017). Deliberative Platform Design: The Case Study of the Online Discussions in Decidim Barcelona. _Social Informatics_, 277–287. https://doi.org/10.1007/978-3-319-67256-4_22
+
.Abstract
[%collapsible]
====
With the irruption of ICTs and the crisis of political representation, many online platforms have been developed with the aim of improving participatory democratic processes. However, regarding platforms for online petitioning, previous research has not found examples of how to effectively introduce discussions, a crucial feature to promote deliberation. In this study we focus on the case of Decidim Barcelona, the online participatory-democracy platform launched by the City Council of Barcelona in which proposals can be discussed with an interface that combines threaded discussions and comment alignment with the proposal. This innovative approach allows to examine whether neutral, positive or negative comments are more likely to generate discussion cascades. The results reveal that, with this interface, comments marked as negatively aligned with the proposal were more likely to engage users in online discussions and, therefore, helped to promote deliberative decision making.
====

* Borge, R., Balcells, J., Padró-Solanet, A., Batlle, A., Orte, A., & Serra, R. (n.d.). _La participación política a través de la plataforma Decidim: análisis de 11 municipios catalanes_.

== Media 

* Calleja-López, A., Monterde, A., & Barandiaran, X. E. (2017, October 18). _De las redes sociales a las redes (tecno)políticas: redes de tercera generación para la democracia del siglo XXI_ [Text]. http://tecnopolitica.net/content/de-las-redes-sociales-las-redes-tecnopol%C3%ADticas-redes-de-tercera-generaci%C3%B3n-para-la

* _TIPS - Cultura digital - La democracia 2.0_. (2017, February 2). http://www.rtve.es/alacarta/videos/tips/tips-cultura-digital-democracia-20/3896837/
+
.Abstract
[%collapsible]
====
Bruno Sokolowicz presenta varias plataformas digitales de democracia participativa y entrevista a Xabier Barandiaran, experto en innovación democrática.
====

* Bravo, E. (2016, July 20). _Cómo mejorar Barcelona con la participación de sus ciudadanos_ [Magazzine]. http://www.yorokobu.es/barcelona-participacion/

* Barandiaran, X. E., Pereira, A., Monterde, A., & Calleja-López, A. (2016). _Plan de desarrollo Decidim Barcelona_. Ajuntament de Barcelona City Council. https://decidim-barcelona.s3.amazonaws.com/uploads/decidim/attachment/file/54/Plan_desarrollo_decidim.pdf
+
.Abstract
[%collapsible]
====
Este documento detalla el futuro desarrollo de la plataforma digital de participación de l´Ajuntament de Barcelona, decidim.barcelona (disponible en URL https://decidim.barcelona). Los principales objetivos de la plataforma son articular, estandarizar, visualizar y comunicar todos los procesos de participación del Ajuntament de Barcelona y de la ciudad ofreciendo un servicio de infraestructura digital para la democracia directa y participativa a todas las escalas territoriales y asociativas de Barcelona. El documento detalla los objetivos de la plataforma, el flujo de desarrollo, las funcionalidades previstas, y un código ético-político.
====

* Participa Pamplona. (2017a, July 18). _Decidim Barcelona (Xabier Barandiaran)_. https://www.youtube.com/watch?v=zQYvdwGsg8M
+
.Abstract
[%collapsible]
====
1a Jornada de tecnología y democracia (24/05/2017). Infraestructuras digitales para la democracia. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona.
====

* Participa Pamplona. (2017b, July 18). _Hacia una democracia participativa inteligente y democrática (Asier Gallastegui y Asier Amezaga)_. https://www.youtube.com/watch?v=z4FTUt8wnRs
+
.Abstract
[%collapsible]
====
1a Jornada de tecnología y democracia (24/05/2017). Infraestructuras digitales para la democracia. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona.
====

* Participa Pamplona. (2017c, July 18). _Metadecidim. Diseño participativo de la plataforma Decidim Barcelona (Andrés Pereira de Lucena)_. https://www.youtube.com/watch?v=I31yY4ip3rk
+
.Abstract
[%collapsible]
====
1a Jornada de tecnología y democracia (24/05/2017). Infraestructuras digitales para la democracia. Andrés Pereira de Lucena. Presidente de la asociación aLabs, coordinador técnico y arquitecto técnico de Decidim.
====

* Barandiaran, X. E., & Romero, C. (2018, May 17). _Presentació Decidim Ada Lovelace_. https://www.youtube.com/watch?v=-3eh_v339Cg

* Barcelona Activa. (n.d.). _Fòrum d’Economies Col·laboratives Procomuns 2017. Activitat paral·lela 3_. Retrieved January 13, 2018, from https://www.youtube.com/watch?v=IvDsgJcNxnQ

* Govern Digital. (n.d.). _CGDL2018 - Participació ciutadana: com fer de la política quelcom més proper_. Retrieved April 9, 2018, from https://www.youtube.com/watch?v=7LH6OItIrRU
