[bibliography]
= {technical-label}
:page-partial:
include::decidim::partial$l10n.adoc[]

[[refs]]
[[ref-4881969-RCNETHPF]]
* Barandiaran, X. E., Pereira, A., Monterde, A., & Calleja-López, A. (2016). _Plan de desarrollo Decidim Barcelona_. Ajuntament de Barcelona City Council. https://decidim-barcelona.s3.amazonaws.com/uploads/decidim/attachment/file/54/Plan_desarrollo_decidim.pdf +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# Este documento detalla el futuro desarrollo de la plataforma digital de participación de l´Ajuntament de Barcelona, decidim.barcelona (disponible en URL https://decidim.barcelona). Los principales objetivos de la plataforma son articular, estandarizar, visualizar y comunicar todos los procesos de participación del Ajuntament de Barcelona y de la ciudad ofreciendo un servicio de infraestructura digital para la democracia directa y participativa a todas las escalas territoriales y asociativas de Barcelona. El documento detalla los objetivos de la plataforma, el flujo de desarrollo, las funcionalidades previstas, y un código ético-político.pass:[</div>]

[[ref-4881969-RNLU5LZ5]]
* Almela, M., Monterde, A., Linares, J., & Calleja-López, A. (2018). _Administració del Decidim Barcelona_ (p. 82). Universitat Oberta de Catalunya. https://decidim.org/pdf/admin-manual-ca.pdf +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# Aquest document és el manual d’administració de Decidim, la plataforma digital de participació ciutadana per a ciutats i organitzacions. En aquest document es proporcionen els pasos per tal de configurar la plataforma Decidim per a un municipi i administrar els seus processos participatius.pass:[</div>]
