[bibliography]
= {video-talks-label}
:page-partial:
include::decidim::partial$l10n.adoc[]

[[refs]]
[[ref-4881969-S7W4DL9X]]
* Participa Pamplona. (2017a, July 18). _Decidim Barcelona (Xabier Barandiaran)_. https://www.youtube.com/watch?v=zQYvdwGsg8M +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnología y democracia (24/05/2017). Infraestructuras digitales para la democracia. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Decidim Barcelona Xabier Barandiaran. Decidim proiektuaren koordinatzailea eta Bartzelonako Udaleko Partaidetza zinegotziaren aholkulariapass:[</div>]

[[ref-4881969-MWRF8SCE]]
* Participa Pamplona. (2017b, July 18). _Hacia una democracia participativa inteligente y democrática (Asier Gallastegui y Asier Amezaga)_. https://www.youtube.com/watch?v=z4FTUt8wnRs +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnología y democracia (24/05/2017). Infraestructuras digitales para la democracia. Decidim Barcelona Xabier Barandiaran. Coordinador del proyecto Decidim, asesor de la Regiduría de Participación del Ayuntamiento de Barcelona. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Decidim Barcelona Xabier Barandiaran. Decidim proiektuaren koordinatzailea eta Bartzelonako Udaleko Partaidetza zinegotziaren aholkulariapass:[</div>]

[[ref-4881969-E8Y4GUTE]]
* Participa Pamplona. (2017c, July 18). _Metadecidim. Diseño participativo de la plataforma Decidim Barcelona (Andrés Pereira de Lucena)_. https://www.youtube.com/watch?v=I31yY4ip3rk +
pass:[<div class="biblio-abstract">][.biblio-abstract-label]#Abstract.# 1a Jornada de tecnología y democracia (24/05/2017). Infraestructuras digitales para la democracia. Andrés Pereira de Lucena. Presidente de la asociación aLabs, coordinador técnico y arquitecto técnico de Decidim. Teknologia eta demokraziari buruzko 1. jardunaldia (24/05/2017). Demokrazia partizipatiborako azpiegitura digitalak Andrés Pereira de Lucena. aLabs elkarteko lehendakaria eta Dicidimen koordinatzaile teknikoa eta arkitekto teknikoa.pass:[</div>]

[[ref-4881969-T5HNM6YJ]]
* Barandiaran, X. E., & Romero, C. (2018, May 17). _Presentació Decidim Ada Lovelace_. https://www.youtube.com/watch?v=-3eh_v339Cg

[[ref-4881969-R62IC5JN]]
* Barcelona Activa. (n.d.). _Fòrum d’Economies Col·laboratives Procomuns 2017. Activitat paral·lela 3_. Retrieved January 13, 2018, from https://www.youtube.com/watch?v=IvDsgJcNxnQ

[[ref-4881969-2AKQS6QL]]
* Govern Digital. (n.d.). _CGDL2018 - Participació ciutadana: com fer de la política quelcom més proper_. Retrieved April 9, 2018, from https://www.youtube.com/watch?v=7LH6OItIrRU

[[ref-4881969-6NURMIL9]]
* Oikos Denktank. (n.d.). _(W)E-Democracy - speaker 5 (1) - E-democratic cities - Arnau Monterde and Xabier E. Barandiaran_. Retrieved August 30, 2017, from https://www.youtube.com/watch?v=qrQ8ij4Ekag
