= Impressão digital

Embora a plataforma deva mostrar as xref:admin:features/versões. documento[Versions] para quase todos os conteúdos, ainda seria
possível manipular o conteúdo editando diretamente o banco de dados.

Como mitigação deste risco, a plataforma mostra uma impressão digital para alguns domínios importantes, por exemplo, um corpo e título da proposta.

imagem:features/impressão digital/modal.png[Verificar impressão digital]

Seu objetivo é fornecer uma maneira informal de dar um "recibo" a um participante para que ele detecte manipulação. Uma impressão digital é uma representação
de hash do conteúdo. É útil garantir que o conteúdo não tenha sido adulterado, como uma única modificação
resultaria em um valor totalmente diferente. É calculado usando um algoritmo de hashing SHA256. A fim de replicá-lo
, você pode usar uma http://www.md5calc.com/sha256[MD5 calculadora online] e copiar e colar os dados de origem.

== Verificar impressão digital

. Ir para o conteúdo que deseja verificar a impressão digital
. Clique no link "Verificar impressão digital" na barra lateral
imagem:features/impressão digital/sidebar.png[Link para verificação de impressão digital na barra lateral]
. Siga as instruções modal

imagem:features/impressão digital/md5calc.png[captura de tela MD5calc.com]

É possível verificar a impressão digital com outras ferramentas, como a ferramenta de linha de comando do sha256sum.

[source,bash]
----
echo -n '{"body":{"en":"<p><strong>**Is your feature request related to a problem? Please describe.**</strong></p><p>It would be useful to set a character limit on questionnaire answers to provide guidance for users regarding how long their answers should be.</p><p><br></p><p><strong>**Describe the solution you\'d like**</strong></p><p>To have a number input field next to each question in the admin, labeled \\"Character limit\\", by default set to zero (no limit), which determines the maximum characters the user answers to those questions can have.</p><p><br></p><p><strong> **Describe alternatives you\'ve considered** </strong></p><p>Another possibility could be to define this globally for the questionnaire, setting the character limit for each type of question.</p><p><br></p><p><strong>**Additional context** </strong></p><p>-</p><p><br></p><p><strong> **Could this issue impact on users private data?** </strong></p><p>No</p><p><br></p><p><strong> **Funded by**</strong></p><p>Fundació Bosch i Guimpera</p>"},"title":{"en":"Maximum characters for questionnaire text answers"}}' | sha256sum
----