name: "decidim-documentation"

services:
  docs-app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    volumes:
      - ../:/workspaces/documentation:cached
    ports:
      - "${DEVCONTAINER_APP_PORT:-1313}:1313"
      - "8080:8080"
    command: sleep infinity
