= Willkommen bei der Decidim-Dokumentation

Dies ist die Dokumentationsseite zu Decidim, einer partizipatorischen Demokratieplattform, die ursprünglich von der Stadtverwaltung Barcelonas geschaffen wurde.

Die Plattform ermöglicht es jeder Organisation (Stadtrat, Vereinigung, Universität, NGO, Nachbarschaft oder Genossenschaft), Massenprozesse für die strategische Planung, partizipative Budgetierung, gemeinschaftliche Gestaltung von Vorschriften, städtische Räume und Wahlprozesse zu erstellen. Die Plattform ermöglicht es jeder Organisation (Stadtrat, Vereinigung, Universität, NGO, Nachbarschaft oder Genossenschaft) Massenprozesse für die strategische Planung zu erstellen partizipative Budgetierung, gemeinschaftliche Gestaltung für Vorschriften, städtische Räume und Wahlprozesse.

== Neu bei Decidim?

Sie haben die Dokumentation für Decidim gefunden. Erfahren Sie mehr über das Projekt unter https://decidim.org[decidim.org].

[NOTE]
====
Dies ist die Dokumentation für den `develop` Zweig. Sie können diese Dokumentationsseite auch in anderen Versionen ansehen: xref:v0.32@ROOT:index.adoc[v0.32]
====

// * Read the xref:ROOT:getting-started.adoc[Getting Started guide]

Die Dokumentation umfasst xref:install:index.adoc[Installation], xref:configure:index.adoc[Konfiguration] und xref:admin:index.adoc[Betrieb] Ihrer eigenen Decidim-Website.

Wenn Sie Änderungen am Quellcode vornehmen möchten, haben wir auch eine Dokumentation für xref:develop:guide.adoc[Entwickelnde] zu bieten.

Wenn Sie eine Organisation sind, die Decidim verwenden möchte, oder ein Entwickler, der an der Zusammenarbeit an der Software interessiert ist, bitte https://decidim.org/contact[get in touch].

Decidim ist eine Gemeinschaftsanstrengung. Wenn Sie also Fehler in diesen Anleitungen finden, lassen Sie es uns bitte unter hola [at] decidim [dot] org wissen. Jede Hilfe ist willkommen. Wenn Sie ein GitHub-Benutzer sind, können Sie sogar Änderungen an dieser Website mit dem Link Bearbeiten auf jeder Seite vorschlagen.