= Pages d'information

include::partial$legacy.adoc[]

Nous vous proposons ici trois pages d'information que vous pouvez utiliser comme modèle ou réutiliser en remplaçant le texte surligné en jaune par le texte correct. Vous pouvez trouver les mêmes documents en espagnol ou catalan dans leur document Administering Decidim respectif.

== Informations/FAQ

[[t.6a4146f0a2c8ecae39afa2642bcb7f700ef842af]][[t.0]]

[width="100%", cols="100%"]
|===
|_FAQS (EN)_

a|Si vous souhaitez participer à des processus participatifs et avoir votre parole, inscrivez-vous! Notez que pour utiliser certaines fonctions de certains processus (comme le vote et la priorisation), vous devrez vérifier que vous êtes enregistré auprès de #Name of the Municipality/ Organization#, en suivant une étape très simple.

*Qu'est-ce que #Nom de la Municipalité / Organisation ?#*

Une plate-forme pour construire un #Nom plus participatif de la Municipalité/Organisation#, avec une vision partagée et pour approfondir la démocratie participative locale.

#Platformname# est une plate-forme participative basée sur le code ouvert. Les citoyens peuvent voir comment il est construit et peut le réutiliser ou l'améliorer. https://www.google.com/url?q=https://github.com/AjuntamentdeBarcelona/decidim.barcelona&sa=D&ust=1526042251888000[Consultez le code ici sur GitHub].

*Comment puis-je participer au nom de la plateforme ?*

Être informé

* Consulter les processus participatifs actifs.
* Parcourez les propositions faites par d'autres citoyens
* Accédez aux données et aux documents des réunions en face à face, aux discussions et aux débats qui y ont lieu.
* Recherchez le contenu qui vous intéresse, par district, sujet et balises.

Participez

* Faites de nouvelles propositions.
* Proposez des arguments en faveur ou contre ou contre vos pensées générales.
* Partagez les propositions sur les médias sociaux.

a|Suivez les propositions existantes

* Suivez les propositions existantes : celles lancées sur la plate-forme et celles générées par les réunions en face à face.
* Après les réunions en face à face, vous pouvez suivre les progrès des discussions et des débats ainsi que les contributions générées.
* Cochez une proposition qui vous intéresse et suivez toute sa progression, des commentaires faits par d'autres jusqu'aux documents finaux.

*Que sont-ils...?*

*Processus participatifs*

*#Platformname#* activités qui impliquent des citoyens et qui sont réalisées en plusieurs étapes : information, diagnostic, contributions, décisions, résultats et évaluation des propositions.

*Assembles*

Salons et corps participatifs permanents.

*Réunions en face à face :*

Réunions et sessions de travail pour contribuer à des processus participatifs actifs.

*Enquêtes*

Questionnaire pour fournir de l'information et partager votre opinion.

*Discussions et débats*

Espaces numériques pour être informé et décider des propositions dans les processus qui ont cette fonction activée.

*Propositions,

Contributions que vous pouvez apporter en tant qu'utilisateur. Dans certains cas, vous pourrez recevoir des votes d'autres utilisateurs. Certains d'entre eux auront une fonction de prise de décision et d'autres une fonction purement consultative. Chaque processus aura ses propres règles caractéristiques.

*Commentaires*

Contributions que vous pouvez apporter en tant qu'utilisateur en réponse à une proposition ou à une discussion et à un débat.

*Ma vérification de résidence ne fonctionne pas.*

Vérifiez les possibilités suivantes :

* Avez-vous entré votre numéro d'identité national ou votre document sans espace entre les chiffres, y compris la lettre finale?
* Êtes-vous sûr d'être un résident enregistré dans la municipalité de #Nom de la Municipalité/Organisation#? (La municipalité est géographiquement plus petite que la zone métropolitaine de Barcelone et la province de Barcelone)
* Il peut y avoir un problème avec vos données dans le registre de résidence. Consultez le bureau CITIZEN le plus près de chez vous et confirmez que vos informations d'inscription sont correctes.

Si toutes les étapes ci-dessus ne résolvent pas le problème, écrivez-nous à #Email# ou venez aux discussions et débats en face à face pour chaque processus.

*Je ne suis pas un résident inscrit au #Nom de la Municipalité / Organisation#; pourquoi ne puis-je pas voter pour les propositions?*

Seuls les résidents inscrits au #Nom de la Municipalité / Organisation# sont autorisés à voter dans les processus sur lesquels les propositions peuvent être votées. Quand il s'agit de questions qui affectent les décisions à prendre qui sont spécifiques à la ville, ce sont les habitants de la ville qui doivent prendre part à de telles décisions.

Il est vrai qu'il y a des gens qui ne sont pas inscrits #Nom de la Municipalité/Organisation# résidents qui peuvent encore être affectés par ces décisions, mais le Registre est le recensement disponible le plus large que nous ayons dans #Nom de la Municipalité/Organisation#: il nous permet d'atteindre le nombre maximum de personnes tout en garantissant que le processus participatif est sécurisé. D'un autre côté, tous les processus lancés depuis la plate-forme n'exigent pas que leurs participants soient des résidents inscrits dans la ville.

*Je ne suis pas inscrit #Nom de la Municipalité / Organisation# résident. Puis-je participer ?*

Oui, vous pouvez y participer même si vous n'êtes pas un résident inscrit. Vous pouvez participer à plusieurs processus activés, à des discussions et débats en face à face, et vous pouvez lancer une proposition, sans avoir à être un résident enregistré. Ce n'est que dans certains processus que le vote de propositions se limite aux résidents inscrits, tout comme seuls les résidents inscrits peuvent voter aux élections municipales.

*Pourquoi dois-je vérifier mon compte ?*

Vous avez besoin d'un compte utilisateur pour utiliser la plateforme. Vous pouvez faire plus ou moins de choses en fonction du degré de vérification :

* Si vous vous inscrivez sur le site Web par une adresse e-mail sans fournir aucune information supplémentaire (donc le processus de vérification n'est pas effectué), vous pourrez commenter et débattre des propositions.
* Si après l'enregistrement, vous avez effectué la vérification de base, c.-à-d. vous avez vérifié votre résidence par le biais de la plateforme (plus d'informations à "Comment puis-je créer et vérifier mon compte ? ), vous pouvez voter pour des propositions dans des processus qui sont faisables (dans certains processus).
* Vous pouvez toujours participer en personne et à n'importe quelle réunion en face à face, il y a pour chaque processus participatif. Les contributions faites face à face seront collectées, publiées et accessibles à la plate-forme.

*Ai-je besoin d'un téléphone portable ou d'un accès à Internet pour y participer ?*

Non. Vous pouvez mener à bien toute action relative aux propositions - que ce soit pour créer, soutenir, voter pour ou être informé à leur sujet - face à face lors de toutes les discussions et débats qui ont lieu. Vous pouvez également créer un compte utilisateur entièrement vérifié si vous souhaitez utiliser la plateforme.

*Comment créer et vérifier mon compte ?*

La première étape est de créer un compte. Créez le compte et remplissez les informations qui vous sont demandées. Vous devez cocher la case indiquant que vous acceptez nos conditions d'utilisation. Lors de la création d'un nouveau compte, un e-mail sera envoyé à l'adresse que vous avez spécifiée, et vous devrez cliquer sur le lien qu'il contient (le lien « Confirmer mon compte ») pour terminer la création du compte.

Une fois que votre compte de base a été créé et que vous vous êtes connecté en utilisant votre adresse e-mail et votre mot de passe, le système vous donnera la possibilité d'effectuer une vérification de base. Pour cela, cliquez sur le lien "Mon compte" en haut à droite puis cliquez sur le bouton "Vérifier mon compte".

Certains processus, le cas échéant, vous demanderont également d'entrer vos données de résidence, pour vérifier que vous êtes un résident enregistré au #Nom de la Municipalité / Organisation# (il est important de saisir le numéro du document avec la lettre et votre date de naissance, et cochez la case indiquant que vous acceptez l'accès au Registre Municipal). Si vos données sont correctes, votre compte vous permettra de soutenir les propositions.

*J'ai oublié mon mot de passe et mon compte ne fonctionne pas. Que puis-je faire?*

Vous pouvez demander un nouveau mot de passe qui sera envoyé à votre adresse e-mail. Si la solution ci-dessus ne fonctionne pas, vous pouvez nous envoyer un e-mail à #Email#, et nous résoudrons le problème lié à votre compte. Les processus qui incluent des réunions en face à face sont ouverts à vous pour y assister et y participer, sans que vous ayez à vous inscrire à la plateforme.

*Comment puis-je changer mon adresse e-mail, mon nom d'utilisateur, mon mot de passe, désabonner ou activer/désactiver les notifications qui sont envoyées à l'adresse e-mail ?*

Cliquez sur le lien « Entrée », entrez votre adresse e-mail et votre mot de passe et cliquez sur le bouton « Entrée ». Une fois que vous l'avez fait, cliquez sur le lien "Mon compte", où vous trouverez toutes les options, vous permettant de changer votre adresse e-mail ou votre nom d'utilisateur, de vous désabonner ou d'activer/désactiver les notifications. Une fois que vous avez effectué les modifications appropriées, assurez-vous de cliquer sur le bouton « Enregistrer les modifications ».

*Je ne peux pas créer mon compte correctement.*

Consultez la section "Ma vérification de résidence ne fonctionne pas", au cas où le problème réside dans cette étape; en général, c'est le problème le plus fréquent. Si cela ne résout pas votre problème, consultez la section "Comment créer et vérifier mon compte", pour vous assurer que vous suivez les étapes correctement. Si le problème persiste, envoyez-nous un e-mail à #Email#, et nous vous aiderons.
|===

[[h.mkf6otb3mhlh]]
== Conditions d'utilisation

[[t.0c2d2bc083254e4010a82a1ac81ebd7f18f135ee]][[t.1]]

[width="100%", cols="100%"]
|===
|_Conditions d'utilisation (EN)_

a|Aspects juridiques et conditions d'utilisation pour la plate-forme participative #Platformname# à #Nom de la Municipalité/Organisation# Conseil municipal.

(ceux que vous recommandent les services juridiques. Vous pouvez utiliser le https://www.google.com/url?q=https://decidim.barcelona/pages/terms-and-conditions&sa=D&ust=1526042251902000[Decidim.Barcelona conditions d'utilisation] comme modèle).
|===

[[h.3oy7u29]]
== Comment fonctionne la plateforme

[[t.44b67a895959076674b8c3aa044e22bbd448f440]][[t.2]]

[width="100%", cols="100%"]
|===
|_Accessibilité (EN)_

a|Cela fait référence au design et au contenu de la page Web, qui doivent être accessibles (sans aucun obstacle visuel ou technologique et pour le plus grand nombre possible d'utilisateurs), et aux règlements standards (WAI, Web Accessibility Initiative).

Exemple Decidim.Barcelona https://www.google.com/url?q=https://www.decidim.barcelona/pages/accessibility&sa=D&ust=1526042251903000[Accessibility].
|===