= {page-component-title}
include::decidim::partial$l10n.adoc[]

// tag::subtitle[]

ifeval::["{page-subtitle}" != ""]
[.lead]
{page-subtitle}
endif::[]

// end::subtitle[]

// tag::summary[]

ifeval::["{description}" != ""]
== Summary

[abstract]
{description}
endif::[]

// end::summary[]

// tag::metadata[]

== Metadata

[cols="20,80"]
|===
| Title                                 | *{page-component-title}*

ifeval::["{page-subtitle}" != ""]
| Subtitle                              | {page-subtitle}
endif::[]

ifeval::["{page-component-version}" != "master"]
| Version                               | {page-component-version}
endif::[]

ifeval::["{revdate}" != ""]
| Date                                  | {revdate}
endif::[]

ifeval::["{page-editors}" != ""]
| Editors                               | {page-editors}
endif::[]

| *Authors*                             | *{authors}*

ifeval::["{page-contributors}" != ""]
| Contributors                          | {page-contributors}
endif::[]

ifeval::["{page-proofreaders}" != ""]
| Proofreaders                          | {page-proofreaders}
endif::[]

ifeval::["{page-participants}" != ""]
| xref:decidim:contributing:docs/authorship-criteria.adoc#participants[Participants]
| {page-participants}
endif::[]

ifeval::["{page-translators}" != ""]
| Translators                           | {page-translators}
endif::[]

| Keywords                              | {keywords}

ifeval::["{page-history}" != ""]
| Document history                      | {page-history}
endif::[]

ifeval::["{page-zotero-id}" != ""]
| How to cite                           | {page-zotero-id}
endif::[]

| Copyleft
a| _{page-copyright-ownership}_, under a
ifeval::["{page-license-alternative}" == ""]
_{page-license}_ license.
endif::[]
ifeval::["{page-license-alternative}" != ""]
_{page-license}_ and a _{page-license-alternative}_.
endif::[]

[discrete]
=== Creative Commons Attribution-ShareAlike 4.0 International License (CC-BY-SA-4.0)

You are free to copy and redistribute the material in any medium or format, remix, transform and build upon material, for any purpose, even commercially.
The licensor may not revoke these freedoms as long as you comply with the licence's terms.
Under the following conditions: a) Attribution: you must provide an appropriate acknowledgement of the authorship, provide a link to the licence and state whether any changes have been made.
You may do that in any reasonable way, but not in a way that would suggest you have the licensor's support or receive it for the use you are making; b) ShareAlike: where you remix change or create from the material, you will have to disseminate your contributions under the same licence as the original.
There are no additional restrictions, you may not apply legal terms or technological measures that legally restrict others from doing anything the licence permits.
You can find full licences on the following links: https://creativecommons.org/licenses/by-sa/4.0/deed.

[discrete]
=== GNU Free Documentation Licence (GFDL-1.3-or-later)

You are permitted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation Licence, version 1.3 or any other version subsequently published by the Free Software Foundation; without Invariant Sections or Front-Cover Texts, or Back-Cover Texts either.
You can find a copy of the licence on http://www.gnu.org/copyleft/fdl.html.
|===

// end::metadata[]
