= Certificados de asistencia

Los administradores pueden crear certificados de asistencia a los participantes.

imagen:espacios/conferencias/certificados_of_attendance.png[Certificado de Asistencia (backend)]


.Certificado de Asistencia
|===
|Campo |Tipo |Descripción

|Logo principal
|Requerido
|Logo de la conferencia de la organización que hace el certificado de asistencia.

|Firma
|Requerido
|Imagen de la persona que firma el certificado.

|Firmar fecha
|Requerido
|Fecha de la firma. Formato esperado: dd/mm/aaaa

|Nombre de firma
|Requerido
|Nombre de la persona que firma el certificado.
|===

Después de llenar el formulario, hay un botón para "Enviar certificados de asistencia" a todos los xref:admin:spaces/conferences/registrations/users.adoc[registrations] de la conferencia.

imagen:espacios/conferencias/certificados_of_attendance_button.png[Certificado de Conferencias del botón de envío de asistencia]

Una vez enviado no puede ser reenviado.

imagen:espacios/conferencias/certificados_of_attendance_button_disabled.png[Botón deshabilitado para enviar conferencias de asistencia]

Los certificados de asistencia se envían a los participantes por correo electrónico en formato PDF.

imagen:espacios/conferencias/certificados_of_attendance_pdf.png[Certificado de asistencia (frontend)]