extends: substitution
message: "Use '%s' instead of '%s'."
link: 'https://developers.google.com/style/contractions'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
# Decidim reverses this rule, and do not use contractions, so this is tweaked accordingly.
  aren't: are not
  can't: cannot
  couldn't: could not
  didn't: did not
  don't: do not
  doesn't: does not
  hasn't: has not
  haven't: have not
  how's: how is
  it'd: it would
  isn't: is not
  it'll: it will
  it's: it is
  shouldn't: should not
  that'll: that will
  that's: that is
  they'll: they will
  they're: they are
  wasn't: was not
  we're: we are
  we've: we have
  weren't: were not
  what's: what is
  when's: when is
  where's: where is
  won't: will not
  you'll: you will
