= Introduction
:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

ifndef::env-site,env-github[]
include::_attributes.adoc[] 
endif::[]

include::{partialsdir}/README.adoc[tag=metadata] 

// Start writing here

== Citizen participation in the Network Society

Becoming a network(ed) society. Information and communication technologies (henceforth, ICTs) and their associated practices are bringing about irreversible changes to the social and political landscape. From the smallest residents’ association to the most intensive electoral campaign, from a neighbourhood organisation or social movement to the European Union, political relations are being increasingly determined by the use of digital devices and technologies. It seems that the future of democratic participation and collective action will be through the development of digital platforms and hybrid processes, which renovate traditional practices and combine them with digital ones (Fuchs, 2007).

This transition coincides with the decline of representative systems over the last few decades (Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015), which has contributed to the questioning of the legitimacy and sense of democracy itself, reduced and often identified with this system (Crouch, 2004; Keane, 2009; Streeck, 2016). Several authors have used the terms “post-representation" to refer to the emptying of power and meaning of the representative institutions that go from globalisation to disaffection and divestment of citizens (Brito Vieira and Runciman, 2008; Keane, 2009; Rosanvallon , 2011; Tormey, 2015). The various attempts to boost participation have proved unequal to the task of reversing these trends (Keane, 2011; Tormey, 2015).

This long-running political crisis comes on the back of the financial and economic crisis of 2008, and is directly linked to this earlier crisis. Even so, millions of people mobilised in the face of the crisis, intent not only on demanding but also on experimenting and building a real democracy. The key development here was the 15M network-movement. It is in the context of technological hypermediation that information and communication technologies, used in the 1980s and 1990s to accelerate financial flows and globalisation (Castells, 1996), became crucial spaces and devices for a multitudinous re-appropriation of policy, as well as democratic experimentation (Martinet Ros et al., 2015).

After four years of numerous successes and failures, new political citizen initiatives in May 2015 managed to take power in Spain’s main cities, including Barcelona. In this respect they were riding on the tide of countries such as Iceland, where the economic crisis had led to a period of citizen re-appropriation of the institutions and fertile democratic innovation, based on an intense and creative use of ICTs.

Since 15M, most of the experiments aimed at introducing new forms of participatory and deliberative democracy (Barber, 1984; Habermas, 1994, 1996; Della Porta 2013) have been technologically mediated. As can be seen from the case of Iceland (as well as others, such as Finland), the democratising processes of citizen mobilisation and empowerment require technopolitical coordination (Rodotà 1997; Martinet Ros et al., 2015) to achieve their maximum richness and capacity. Technopolitics stems from the politicisation of technologies and technological re-assemblage of politics as well as the co-development and co-production of politics and technologies. As for forms of technopolitical participation and deliberation, digital and face-to-face practices, spaces and processes connect to and feed back from one another, acquiring a multi-layered dimension. These participatory devices are geared towards increasing the number, variety and parity of players that "take part" in the city’s common government, expanding and enriching the areas, forms and periods in which it takes place and helping to boost a collective intelligence (Levy, 1997) capable of taking on the complexity of contemporary urban life. Technopolitics needs to tackle the numerous limits of what has been called “digital democracy" (Hindman, 2008) starting by freeing itself from the technocentric and technooptimistic narratives around digitally mediated participation.

New participatory processes are being built within a context full of opportunities and fraught with risks. The 2015 government programme and Municipal Action Programme (PAM) for 2016-2019 drawn up for the city of Barcelona gives centre stage to participation and, more specifically, innovation and the development of new democratic participatory models. PAM, ​​the development of which involved thousands of people, meets a clear social demand that calls for ​​a thorough redesign of the democratic system and its participatory mechanisms. This, however, is occurring in a context defined by: a) large politically, economically and socially excluded population sectors; b) increasing difficulty accessing participation as a result of the economic-crisis situation; c) a crisis over the legitimacy and operability of the representative democratic system and public authorities; d) an enormous technological dependency on private corporate infrastructures and services; e) a legal and political context adverse to direct democracy, social independence and territorial sovereignty; f) an abysmal institutional disadvantage in understanding social complexities through techniques analysing social-behaviour data and models that big technological companies and digitally coordinated services possess.

[[h.2et92p0]]
== Data Control and digital infrastructures for democracy

In the context of new configurations of informational capitalism (Castells, 1996), so-called “data capitalism" (Lohr, 2015; Morozov, 2015) or "surveillance capitalism" (Zuboff, 2015), the new digital infrastructures of democracy run the risk of contributing to dynamics contrary to such principles as privacy and technological sovereignty. Exclusive, closed and opaque platforms geared towards exploiting social activities for corporate profit are operating as non-democratic spaces occupying more and more areas of social life. This model is particularly dangerous in relation to the new infrastructures and processes of democracy that we are talking about.

Compared to the exclusive and corporate infrastructural model, the public commons model, which we believe decidim.barcelona’s development needs to be inspired by, ​​is geared towards developing platforms where design, ownership and management are free, open and participatory, shared between public workers and citizens (organised or not). Under this model, not only the platform's code but also the data that are generated in it are processed and appropriated according to the logic of public and common management. The opening-up of everything and anything to participation, the hallmark of the commons as a political principle (as opposed to the private and even state-public sphere --- Laval & Dardot, 2015), seems to be a basic condition for participatory infrastructures to be fully functional. Participation has to be recursive here: it needs to help to define and establish the infrastructural conditions of its own existence and to affect the design, development and management of digital participatory platforms as well as the processes and results (e.g. data) that are generated in them.

Put in the hands of large digital-service corporations, the algorithmic organisation of social life and the area we are concerned with, political participation, poses a risk to democracy and technological sovereignty that only a public commons effort in digital infrastructures can reverse. Only platforms based on free, open, transparent, secure and public-commons management software offer guarantees when it comes to building democracies of greater quality. The democracy of the future has to be built, then, on democratic infrastructures.
