= Hintergrund

:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

== Bürgerbeteiligung in der Netzwerkgesellschaft

Zu einer vernetzten Gesellschaft werden. Informations- und Kommunikationstechnologien (fortan IKT) und ihre damit verbundenen Praktiken bringen unumkehrbare Veränderungen in der sozialen und politischen Landschaft mit sich. Von der kleinsten Bürgervereinigung bis zum intensivsten Wahlkampf, von einer Nachbarschaftsorganisation oder sozialen Bewegung bis hin zur Europäischen Union, werden die politischen Beziehungen zunehmend durch den Einsatz digitaler Geräte und Technologien bestimmt. Es scheint, dass die Zukunft der demokratischen Teilhabe und des kollektiven Handelns durch die Entwicklung digitaler Plattformen und hybrider Prozesse erfolgen wird, die traditionelle Praktiken erneuern und mit digitalen kombinieren (Fuchs, 2007).

Dieser Übergang fällt mit dem Niedergang der repräsentativen Systeme in den letzten Jahrzehnten (Norris, 1999; Pharr & Putnam, 2000; Tormey, 2015) zusammen, der zur Infragestellung der Legitimität und des Sinns der Demokratie selbst beigetragen hat, die reduziert und oft mit diesem System identifiziert wird (Crouch, 2004; Keane, 2009; Streeck, 2016). Mehrere Autoren haben die Begriffe „Post-Repräsentation“ verwendet, um auf die Entleerung von Macht und Bedeutung der repräsentativen Institutionen hinzuweisen, die von der Globalisierung zur Unzufriedenheit und Desinvestition von Bürgern gehen (Brito Vieira und Runciman, 2008; Keane, 2009; Rosanvallon , 2011; Tormey, 2015). Die verschiedenen Versuche, die Beteiligung anzukurbeln, haben sich als ungeeignet erwiesen, diese Trends umzukehren (Keane, 2011; Tormey, 2015).

Diese seit langem andauernde politische Krise kommt auf den Rücken der Finanz- und Wirtschaftskrise von 2008 und steht in direktem Zusammenhang mit dieser früheren Krise. Trotzdem mobilisierten Millionen von Menschen angesichts der Krise, mit der Absicht, nicht nur zu fordern, sondern auch zu experimentieren und eine echte Demokratie aufzubauen. Die Schlüsselentwicklung war hier die 15M Netzwerkbewegung. Vor dem Hintergrund der technologischen Hypermediation wurden Informations- und Kommunikationstechnologien, die in den 1980er- und 1990er-Jahren zur Beschleunigung von Finanzströmen und der Globalisierung eingesetzt wurden (Castells, 1996), zu entscheidenden Räumen und Instrumenten für eine vielschichtige Wiederaneignung der Politik sowie für demokratische Experimente (Martinet Ros et al., 2015).

Nach vier Jahren zahlreicher Erfolge und Misserfolge gelang es im Mai 2015 neuen politischen Bürgerinitiativen in den wichtigsten spanischen Städten, einschliesslich Barcelona, die Macht zu übernehmen. In dieser Hinsicht ritten sie auf der Welle von Ländern wie Island, wo die Wirtschaftskrise zu einer Zeit der Wiederaneignung der Institutionen durch die Bürger und fruchtbarer demokratischer Innovation geführt hatte, basierend auf einer intensiven und kreativen Nutzung von IKT.

Seit 15M waren die meisten Experimente, die auf die Einführung neuer Formen der partizipatorischen und deliberativen Demokratie abzielten (Barber, 1984; Habermas, 1994, 1996; Della Porta 2013), technologisch vermittelt. Wie aus dem Fall Islands (ebenso wie aus anderen Ländern wie Finnland) hervorgeht, erfordern die Demokratisierungsprozesse der Mobilisierung und Stärkung der Bürgerinnen und Bürger eine technopolitische Koordination (Rodotà 1997; Martinet Ros et al., 2015), um ihren maximalen Reichtum und ihre maximale Kapazität zu erreichen. Technopolitik rührt von der Politisierung von Technologien und technologischen Neuzusammensetzungen der Politik sowie von der Ko-Entwicklung und Ko-Produktion von Politik und Technologie her. Was die Formen der technopolitischen Partizipation und Deliberation betrifft, so verbinden sich digitale und persönliche Praktiken, Räume und Prozesse miteinander und leiten sich gegenseitig ab, wodurch sie eine mehrschichtige Dimension erlangen. Diese partizipativen Instrumente zielen darauf ab, die Anzahl, Vielfalt und Parität der Akteure zu erhöhen, die an der gemeinsamen Verwaltung der Stadt teilhaben, die Bereiche, Formen und Zeiträume, in denen dies geschieht, zu erweitern und zu bereichern, und dazu beizutragen, eine kollektive Intelligenz (Levy, 1997) zu fördern, die in der Lage ist, die Komplexität des heutigen urbanen Lebens zu bewältigen. Die Technopolitik muss die zahlreichen Grenzen dessen angehen, was als „digitale Demokratie“ (Hindman, 2008) bezeichnet wurde, indem sie sich zunächst von den technozentrischen und technooptimistischen Erzählungen rund um digital vermittelte Beteiligung befreit.

Neue partizipatorische Prozesse werden in einem Kontext voller Chancen und voller Risiken aufgebaut. Das für die Stadt Barcelona aufgestellte Regierungsprogramm und das städtische Aktionsprogramm (PAM) für 2016-2019 räumt der Beteiligung einen zentralen Platz ein, genauer gesagt der Innovation und der Entwicklung neuer demokratischer Beteiligungsmodelle. PAM, an dessen Entwicklung Tausende von Menschen beteiligt waren, kommt einer klaren sozialen Forderung nach, die eine gründliche Neugestaltung des demokratischen Systems und seiner partizipatorischen Mechanismen verlangt. Dies geschieht jedoch in einem Kontext, der von a) grossen politischen, wirtschaftlichen und sozial ausgegrenzten Bevölkerungssektoren definiert wurde; b) zunehmende Schwierigkeiten beim Zugang zu Beteiligung infolge der wirtschaftlichen Krise; c) eine Krise der Legitimität und Funktionsfähigkeit des repräsentativen demokratischen Systems und der öffentlichen Behörden; d) eine enorme technologische Abhängigkeit von privaten Unternehmensinfrastrukturen und -dienstleistungen, e) ein juristischer und politischer Kontext, der der direkten Demokratie, der sozialen Unabhängigkeit und der territorialen Souveränität abträglich ist; f) ein gravierender institutioneller Nachteil beim Verständnis sozialer Komplexitäten durch Techniken zur Analyse von Daten des Sozialverhaltens und von Modellen, die grosse technologische Unternehmen und digital koordinierte Dienstleistungen besitzen.

[[h.2et92p0]]
== Datenkontrolle und digitale Infrastrukturen für die Demokratie

Im Kontext neuer Konfigurationen des Informationskapitalismus (Castells, 1996), so genannter „Datenkapitalismus“ (Lohr, 2015; Morozov, 2015) oder "Überwachungskapitalismus" (Zuboff, 2015), die neuen digitalen Infrastrukturen der Demokratie laufen Gefahr, zu einer Dynamik beizutragen, die gegen die Prinzipien der Privatsphäre und der technologischen Souveränität verstösst. Exklusive, geschlossene und undurchsichtige Plattformen, die darauf abzielen, soziale Aktivitäten zum Unternehmensgewinn zu nutzen, funktionieren als undemokratische Räume, die immer mehr Bereiche des gesellschaftlichen Lebens besetzen. Dieses Modell ist besonders gefährlich im Hinblick auf die neuen Infrastrukturen und Prozesse der Demokratie, über die wir hier sprechen.

Im Vergleich zum exklusiven und unternehmerischen Infrastrukturmodell orientiert sich das öffentliche Gemeingut-Modell, an dem sich die Entwicklung von decidim.barcelona unseres Erachtens inspirieren sollte, an der Entwicklung von Plattformen, auf denen Gestaltung, Eigentum und Verwaltung frei, offen und partizipativ sind und zwischen öffentlich Beschäftigten und Bürgerinnen und Bürgern (organisiert oder nicht) geteilt werden. Unter diesem Modell werden nicht nur der Code der Plattform, sondern auch die darin erzeugten Daten gemäss der Logik des öffentlichen und gemeinsamen Managements verarbeitet und angeeignet. Die Öffnung von allem und jedem für die Beteiligung, das Kennzeichen des Gemeinguts als politisches Prinzip (im Gegensatz zur privaten und sogar staatlich-öffentlichen Sphäre --- Laval & Dardot, 2015), scheint eine Grundvoraussetzung dafür zu sein, dass partizipative Infrastrukturen voll funktionsfähig sind. Die Beteiligung muss hier rekursiv sein: Sie muss dabei helfen, die infrastrukturellen Bedingungen ihrer eigenen Existenz zu definieren und zu etablieren, und das Design, die Entwicklung und die Verwaltung digitaler Beteiligungsplattformen sowie die darin generierten Prozesse und Ergebnisse (z.B. Daten) zu beeinflussen.

In die Hände grosser Unternehmen digitaler Dienstleistungen gelegt, stellen die algorithmische Organisation des gesellschaftlichen Lebens und der Bereich, mit dem wir uns hier befassen – die politische Beteiligung –, eine Gefahr für die Demokratie und die technologische Souveränität dar, die nur durch gemeinschaftlich-öffentliche Anstrengungen im Bereich der digitalen Infrastrukturen rückgängig gemacht werden kann. Nur Plattformen, die auf einer freien, offenen, transparenten, sicheren und öffentlichen Verwaltungssoftware basieren, bieten Garantien für den Aufbau von Demokratien von grösserer Qualität. Die Demokratie der Zukunft muss also auf demokratischen Infrastrukturen aufgebaut werden.